from _typeshed import Incomplete

logger: Incomplete
GETATTR: str
GET: str

class PathExtractionError(ValueError): ...
class RootCanNotBeModified(ValueError): ...

DEFAULT_FIRST_ELEMENT: Incomplete

def extract(obj, path): ...
def parse_path(path, root_element=..., include_actions: bool = ...): ...
def stringify_element(param, quote_str: Incomplete | None = ...): ...
def stringify_path(path, root_element=..., quote_str: str = ...): ...
