import json
import pickle
from _typeshed import Incomplete
from deepdiff.helper import TEXT_VIEW as TEXT_VIEW, get_type as get_type, np_float32 as np_float32, np_float64 as np_float64, np_int32 as np_int32, np_int64 as np_int64, strings as strings
from deepdiff.model import DeltaResult as DeltaResult

csv: Incomplete
logger: Incomplete

class UnsupportedFormatErr(TypeError): ...

NONE_TYPE: Incomplete
CSV_HEADER_MAX_CHUNK_SIZE: int
MODULE_NOT_FOUND_MSG: str
FORBIDDEN_MODULE_MSG: str
DELTA_IGNORE_ORDER_NEEDS_REPETITION_REPORT: str
DELTA_ERROR_WHEN_GROUP_BY: str
SAFE_TO_IMPORT: Incomplete
TYPE_STR_TO_TYPE: Incomplete

class ModuleNotFoundError(ImportError): ...
class ForbiddenModule(ImportError): ...

class SerializationMixin:
    def to_json_pickle(self): ...
    @classmethod
    def from_json_pickle(cls, value): ...
    def to_json(self, default_mapping: Incomplete | None = ..., **kwargs): ...
    def to_dict(self, view_override: Incomplete | None = ...): ...
    def pretty(self): ...

class _RestrictedUnpickler(pickle.Unpickler):
    safe_to_import: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def find_class(self, module, name): ...
    def persistent_load(self, persistent_id): ...

class _RestrictedPickler(pickle.Pickler):
    def persistent_id(self, obj): ...

def pickle_dump(obj, file_obj: Incomplete | None = ..., protocol: int = ...): ...
def pickle_load(content: Incomplete | None = ..., file_obj: Incomplete | None = ..., safe_to_import: Incomplete | None = ...): ...
def pretty_print_diff(diff): ...
def load_path_content(path, file_type: Incomplete | None = ...): ...
def save_content_to_path(content, path, file_type: Incomplete | None = ..., keep_backup: bool = ...) -> None: ...

JSON_CONVERTOR: Incomplete

def json_convertor_default(default_mapping: Incomplete | None = ...): ...

class JSONDecoder(json.JSONDecoder):
    def __init__(self, *args, **kwargs) -> None: ...
    def object_hook(self, obj): ...

def json_dumps(item, default_mapping: Incomplete | None = ..., **kwargs): ...

json_loads: Incomplete
