def db() -> None: ...
def list_templates() -> None: ...
def init(directory, multidb, template, package) -> None: ...
def revision(directory, message, autogenerate, sql, head, splice, branch_label, version_path, rev_id) -> None: ...
def migrate(directory, message, sql, head, splice, branch_label, version_path, rev_id, x_arg) -> None: ...
def edit(directory, revision) -> None: ...
def merge(directory, message, branch_label, rev_id, revisions) -> None: ...
def upgrade(directory, sql, tag, x_arg, revision) -> None: ...
def downgrade(directory, sql, tag, x_arg, revision) -> None: ...
def show(directory, revision) -> None: ...
def history(directory, rev_range, verbose, indicate_current) -> None: ...
def heads(directory, verbose, resolve_dependencies) -> None: ...
def branches(directory, verbose) -> None: ...
def current(directory, verbose) -> None: ...
def stamp(directory, sql, tag, revision) -> None: ...
def check(directory) -> None: ...
