#!/usr/bin/env python

import shlex
import subprocess
from typing import List


def run_check_command(command: List[str]) -> None:
    print(f"Running: {shlex.join(command)}")
    subprocess.run(command, check=True)


def read_autoformat_target_paths() -> List[str]:
    with open(".autoformattingrc") as handle:
        return [line.strip() for line in handle.read().splitlines() if line.strip()]


def main():
    autoformatted_paths = read_autoformat_target_paths()
    run_check_command(["black", "--check"] + autoformatted_paths)
    run_check_command(["flake8"])
    run_check_command(["mypy"])
    run_check_command(["pytest"])
    run_check_command(["isort", "--check"] + autoformatted_paths)


if __name__ == "__main__":
    main()
