from _typeshed import Incomplete
from docutils import nodes
from docutils.parsers.rst.directives.images import Figure

class figmplnode(nodes.General, nodes.Element): ...

class FigureMpl(Figure):
    has_content: bool
    required_arguments: int
    optional_arguments: int
    final_argument_whitespace: bool
    option_spec: Incomplete
    def run(self): ...

def visit_figmpl_html(self, node) -> None: ...
def visit_figmpl_latex(self, node) -> None: ...
def depart_figmpl_html(self, node) -> None: ...
def depart_figmpl_latex(self, node) -> None: ...
def figurempl_addnode(app) -> None: ...
def setup(app): ...
