import sqlalchemy as sa
import typing as t
from .pagination import Pagination as Pagination, QueryPagination as QueryPagination

class Query(sa.orm.Query):
    def get_or_404(self, ident: t.Any, description: str | None = ...) -> t.Any: ...
    def first_or_404(self, description: str | None = ...) -> t.Any: ...
    def one_or_404(self, description: str | None = ...) -> t.Any: ...
    def paginate(self, *, page: int | None = ..., per_page: int | None = ..., max_per_page: int | None = ..., error_out: bool = ..., count: bool = ...) -> Pagination: ...
