import matplotlib.table as mtable
from _typeshed import Incomplete
from matplotlib.axes._base import _AxesBase
from matplotlib.axes._secondary_axes import SecondaryAxis as SecondaryAxis
from matplotlib.container import BarContainer as BarContainer, ErrorbarContainer as ErrorbarContainer, StemContainer as StemContainer

class Axes(_AxesBase):
    def get_title(self, loc: str = ...): ...
    def set_title(self, label, fontdict: Incomplete | None = ..., loc: Incomplete | None = ..., pad: Incomplete | None = ..., *, y: Incomplete | None = ..., **kwargs): ...
    def get_legend_handles_labels(self, legend_handler_map: Incomplete | None = ...): ...
    legend_: Incomplete
    def legend(self, *args, **kwargs): ...
    def inset_axes(self, bounds, *, transform: Incomplete | None = ..., zorder: int = ..., **kwargs): ...
    def indicate_inset(self, bounds, inset_ax: Incomplete | None = ..., *, transform: Incomplete | None = ..., facecolor: str = ..., edgecolor: str = ..., alpha: float = ..., zorder: float = ..., **kwargs): ...
    def indicate_inset_zoom(self, inset_ax, **kwargs): ...
    def secondary_xaxis(self, location, *, functions: Incomplete | None = ..., **kwargs): ...
    def secondary_yaxis(self, location, *, functions: Incomplete | None = ..., **kwargs): ...
    def text(self, x, y, s, fontdict: Incomplete | None = ..., **kwargs): ...
    def annotate(self, text, xy, xytext: Incomplete | None = ..., xycoords: str = ..., textcoords: Incomplete | None = ..., arrowprops: Incomplete | None = ..., annotation_clip: Incomplete | None = ..., **kwargs): ...
    def axhline(self, y: int = ..., xmin: int = ..., xmax: int = ..., **kwargs): ...
    def axvline(self, x: int = ..., ymin: int = ..., ymax: int = ..., **kwargs): ...
    def axline(self, xy1, xy2: Incomplete | None = ..., *, slope: Incomplete | None = ..., **kwargs): ...
    def axhspan(self, ymin, ymax, xmin: int = ..., xmax: int = ..., **kwargs): ...
    def axvspan(self, xmin, xmax, ymin: int = ..., ymax: int = ..., **kwargs): ...
    def hlines(self, y, xmin, xmax, colors: Incomplete | None = ..., linestyles: str = ..., label: str = ..., **kwargs): ...
    def vlines(self, x, ymin, ymax, colors: Incomplete | None = ..., linestyles: str = ..., label: str = ..., **kwargs): ...
    def eventplot(self, positions, orientation: str = ..., lineoffsets: int = ..., linelengths: int = ..., linewidths: Incomplete | None = ..., colors: Incomplete | None = ..., alpha: Incomplete | None = ..., linestyles: str = ..., **kwargs): ...
    def plot(self, *args, scalex: bool = ..., scaley: bool = ..., data: Incomplete | None = ..., **kwargs): ...
    def plot_date(self, x, y, fmt: str = ..., tz: Incomplete | None = ..., xdate: bool = ..., ydate: bool = ..., **kwargs): ...
    def loglog(self, *args, **kwargs): ...
    def semilogx(self, *args, **kwargs): ...
    def semilogy(self, *args, **kwargs): ...
    def acorr(self, x, **kwargs): ...
    def xcorr(self, x, y, normed: bool = ..., detrend=..., usevlines: bool = ..., maxlags: int = ..., **kwargs): ...
    def step(self, x, y, *args, where: str = ..., data: Incomplete | None = ..., **kwargs): ...
    def bar(self, x, height, width: float = ..., bottom: Incomplete | None = ..., *, align: str = ..., **kwargs): ...
    def barh(self, y, width, height: float = ..., left: Incomplete | None = ..., *, align: str = ..., data: Incomplete | None = ..., **kwargs): ...
    def bar_label(self, container, labels: Incomplete | None = ..., *, fmt: str = ..., label_type: str = ..., padding: int = ..., **kwargs): ...
    def broken_barh(self, xranges, yrange, **kwargs): ...
    def stem(self, *args, linefmt: Incomplete | None = ..., markerfmt: Incomplete | None = ..., basefmt: Incomplete | None = ..., bottom: int = ..., label: Incomplete | None = ..., use_line_collection: bool = ..., orientation: str = ...): ...
    def pie(self, x, explode: Incomplete | None = ..., labels: Incomplete | None = ..., colors: Incomplete | None = ..., autopct: Incomplete | None = ..., pctdistance: float = ..., shadow: bool = ..., labeldistance: float = ..., startangle: int = ..., radius: int = ..., counterclock: bool = ..., wedgeprops: Incomplete | None = ..., textprops: Incomplete | None = ..., center=..., frame: bool = ..., rotatelabels: bool = ..., *, normalize: bool = ..., hatch: Incomplete | None = ...): ...
    def errorbar(self, x, y, yerr: Incomplete | None = ..., xerr: Incomplete | None = ..., fmt: str = ..., ecolor: Incomplete | None = ..., elinewidth: Incomplete | None = ..., capsize: Incomplete | None = ..., barsabove: bool = ..., lolims: bool = ..., uplims: bool = ..., xlolims: bool = ..., xuplims: bool = ..., errorevery: int = ..., capthick: Incomplete | None = ..., **kwargs): ...
    def boxplot(self, x, notch: Incomplete | None = ..., sym: Incomplete | None = ..., vert: Incomplete | None = ..., whis: Incomplete | None = ..., positions: Incomplete | None = ..., widths: Incomplete | None = ..., patch_artist: Incomplete | None = ..., bootstrap: Incomplete | None = ..., usermedians: Incomplete | None = ..., conf_intervals: Incomplete | None = ..., meanline: Incomplete | None = ..., showmeans: Incomplete | None = ..., showcaps: Incomplete | None = ..., showbox: Incomplete | None = ..., showfliers: Incomplete | None = ..., boxprops: Incomplete | None = ..., labels: Incomplete | None = ..., flierprops: Incomplete | None = ..., medianprops: Incomplete | None = ..., meanprops: Incomplete | None = ..., capprops: Incomplete | None = ..., whiskerprops: Incomplete | None = ..., manage_ticks: bool = ..., autorange: bool = ..., zorder: Incomplete | None = ..., capwidths: Incomplete | None = ...): ...
    def bxp(self, bxpstats, positions: Incomplete | None = ..., widths: Incomplete | None = ..., vert: bool = ..., patch_artist: bool = ..., shownotches: bool = ..., showmeans: bool = ..., showcaps: bool = ..., showbox: bool = ..., showfliers: bool = ..., boxprops: Incomplete | None = ..., whiskerprops: Incomplete | None = ..., flierprops: Incomplete | None = ..., medianprops: Incomplete | None = ..., capprops: Incomplete | None = ..., meanprops: Incomplete | None = ..., meanline: bool = ..., manage_ticks: bool = ..., zorder: Incomplete | None = ..., capwidths: Incomplete | None = ...): ...
    def scatter(self, x, y, s: Incomplete | None = ..., c: Incomplete | None = ..., marker: Incomplete | None = ..., cmap: Incomplete | None = ..., norm: Incomplete | None = ..., vmin: Incomplete | None = ..., vmax: Incomplete | None = ..., alpha: Incomplete | None = ..., linewidths: Incomplete | None = ..., *, edgecolors: Incomplete | None = ..., plotnonfinite: bool = ..., **kwargs): ...
    def hexbin(self, x, y, C: Incomplete | None = ..., gridsize: int = ..., bins: Incomplete | None = ..., xscale: str = ..., yscale: str = ..., extent: Incomplete | None = ..., cmap: Incomplete | None = ..., norm: Incomplete | None = ..., vmin: Incomplete | None = ..., vmax: Incomplete | None = ..., alpha: Incomplete | None = ..., linewidths: Incomplete | None = ..., edgecolors: str = ..., reduce_C_function=..., mincnt: Incomplete | None = ..., marginals: bool = ..., **kwargs): ...
    def arrow(self, x, y, dx, dy, **kwargs): ...
    def quiverkey(self, Q, X, Y, U, label, **kwargs): ...
    def quiver(self, *args, **kwargs): ...
    def barbs(self, *args, **kwargs): ...
    def fill(self, *args, data: Incomplete | None = ..., **kwargs): ...
    def fill_between(self, x, y1, y2: int = ..., where: Incomplete | None = ..., interpolate: bool = ..., step: Incomplete | None = ..., **kwargs): ...
    fill_between: Incomplete
    def fill_betweenx(self, y, x1, x2: int = ..., where: Incomplete | None = ..., step: Incomplete | None = ..., interpolate: bool = ..., **kwargs): ...
    fill_betweenx: Incomplete
    def imshow(self, X, cmap: Incomplete | None = ..., norm: Incomplete | None = ..., *, aspect: Incomplete | None = ..., interpolation: Incomplete | None = ..., alpha: Incomplete | None = ..., vmin: Incomplete | None = ..., vmax: Incomplete | None = ..., origin: Incomplete | None = ..., extent: Incomplete | None = ..., interpolation_stage: Incomplete | None = ..., filternorm: bool = ..., filterrad: float = ..., resample: Incomplete | None = ..., url: Incomplete | None = ..., **kwargs): ...
    def pcolor(self, *args, shading: Incomplete | None = ..., alpha: Incomplete | None = ..., norm: Incomplete | None = ..., cmap: Incomplete | None = ..., vmin: Incomplete | None = ..., vmax: Incomplete | None = ..., **kwargs): ...
    def pcolormesh(self, *args, alpha: Incomplete | None = ..., norm: Incomplete | None = ..., cmap: Incomplete | None = ..., vmin: Incomplete | None = ..., vmax: Incomplete | None = ..., shading: Incomplete | None = ..., antialiased: bool = ..., **kwargs): ...
    def pcolorfast(self, *args, alpha: Incomplete | None = ..., norm: Incomplete | None = ..., cmap: Incomplete | None = ..., vmin: Incomplete | None = ..., vmax: Incomplete | None = ..., **kwargs): ...
    def contour(self, *args, **kwargs): ...
    def contourf(self, *args, **kwargs): ...
    def clabel(self, CS, levels: Incomplete | None = ..., **kwargs): ...
    def hist(self, x, bins: Incomplete | None = ..., range: Incomplete | None = ..., density: bool = ..., weights: Incomplete | None = ..., cumulative: bool = ..., bottom: Incomplete | None = ..., histtype: str = ..., align: str = ..., orientation: str = ..., rwidth: Incomplete | None = ..., log: bool = ..., color: Incomplete | None = ..., label: Incomplete | None = ..., stacked: bool = ..., **kwargs): ...
    def stairs(self, values, edges: Incomplete | None = ..., *, orientation: str = ..., baseline: int = ..., fill: bool = ..., **kwargs): ...
    def hist2d(self, x, y, bins: int = ..., range: Incomplete | None = ..., density: bool = ..., weights: Incomplete | None = ..., cmin: Incomplete | None = ..., cmax: Incomplete | None = ..., **kwargs): ...
    def psd(self, x, NFFT: Incomplete | None = ..., Fs: Incomplete | None = ..., Fc: Incomplete | None = ..., detrend: Incomplete | None = ..., window: Incomplete | None = ..., noverlap: Incomplete | None = ..., pad_to: Incomplete | None = ..., sides: Incomplete | None = ..., scale_by_freq: Incomplete | None = ..., return_line: Incomplete | None = ..., **kwargs): ...
    def csd(self, x, y, NFFT: Incomplete | None = ..., Fs: Incomplete | None = ..., Fc: Incomplete | None = ..., detrend: Incomplete | None = ..., window: Incomplete | None = ..., noverlap: Incomplete | None = ..., pad_to: Incomplete | None = ..., sides: Incomplete | None = ..., scale_by_freq: Incomplete | None = ..., return_line: Incomplete | None = ..., **kwargs): ...
    def magnitude_spectrum(self, x, Fs: Incomplete | None = ..., Fc: Incomplete | None = ..., window: Incomplete | None = ..., pad_to: Incomplete | None = ..., sides: Incomplete | None = ..., scale: Incomplete | None = ..., **kwargs): ...
    def angle_spectrum(self, x, Fs: Incomplete | None = ..., Fc: Incomplete | None = ..., window: Incomplete | None = ..., pad_to: Incomplete | None = ..., sides: Incomplete | None = ..., **kwargs): ...
    def phase_spectrum(self, x, Fs: Incomplete | None = ..., Fc: Incomplete | None = ..., window: Incomplete | None = ..., pad_to: Incomplete | None = ..., sides: Incomplete | None = ..., **kwargs): ...
    def cohere(self, x, y, NFFT: int = ..., Fs: int = ..., Fc: int = ..., detrend=..., window=..., noverlap: int = ..., pad_to: Incomplete | None = ..., sides: str = ..., scale_by_freq: Incomplete | None = ..., **kwargs): ...
    def specgram(self, x, NFFT: Incomplete | None = ..., Fs: Incomplete | None = ..., Fc: Incomplete | None = ..., detrend: Incomplete | None = ..., window: Incomplete | None = ..., noverlap: Incomplete | None = ..., cmap: Incomplete | None = ..., xextent: Incomplete | None = ..., pad_to: Incomplete | None = ..., sides: Incomplete | None = ..., scale_by_freq: Incomplete | None = ..., mode: Incomplete | None = ..., scale: Incomplete | None = ..., vmin: Incomplete | None = ..., vmax: Incomplete | None = ..., **kwargs): ...
    def spy(self, Z, precision: int = ..., marker: Incomplete | None = ..., markersize: Incomplete | None = ..., aspect: str = ..., origin: str = ..., **kwargs): ...
    def matshow(self, Z, **kwargs): ...
    def violinplot(self, dataset, positions: Incomplete | None = ..., vert: bool = ..., widths: float = ..., showmeans: bool = ..., showextrema: bool = ..., showmedians: bool = ..., quantiles: Incomplete | None = ..., points: int = ..., bw_method: Incomplete | None = ...): ...
    def violin(self, vpstats, positions: Incomplete | None = ..., vert: bool = ..., widths: float = ..., showmeans: bool = ..., showextrema: bool = ..., showmedians: bool = ...): ...
    table = mtable.table
    stackplot: Incomplete
    streamplot: Incomplete
    tricontour: Incomplete
    tricontourf: Incomplete
    tripcolor: Incomplete
    triplot: Incomplete
