from sqlite3 import Connection, Cursor
from typing import Iterator

from _typeshed import Incomplete

LOGGER: Incomplete

class Migration:
    sql_code: Incomplete
    def __init__(self, sql_code: str) -> None: ...
    @classmethod
    def from_filename(cls, filename: str) -> Migration: ...
    def run(self, cursor: Cursor) -> None: ...

class Migrations:
    connection: Incomplete
    migration_files: Incomplete
    def __init__(self, connection: Connection) -> None: ...
    def run_necessary_migrations(self) -> None: ...
    def get_relevant_versions(self, cursor: Cursor) -> Iterator[Migration]: ...
    def get_current_version(self, cursor: Cursor) -> int: ...
