from _typeshed import Incomplete
from wtforms.fields import HiddenField

__all__ = ["CSRFTokenField", "CSRF"]

class CSRFTokenField(HiddenField):
    current_token: Incomplete
    csrf_impl: Incomplete
    def __init__(self, *args, **kw) -> None: ...
    def populate_obj(self, *args) -> None: ...
    def pre_validate(self, form) -> None: ...
    def process(self, *args, **kwargs) -> None: ...

class CSRF:
    field_class = CSRFTokenField
    def setup_form(self, form): ...
    def generate_csrf_token(self, csrf_token_field) -> None: ...
    def validate_csrf_token(self, form, field) -> None: ...
