from _typeshed import Incomplete

from .core import CSRF

__all__ = ["SessionCSRF"]

class SessionCSRF(CSRF):
    TIME_FORMAT: str
    form_meta: Incomplete
    def setup_form(self, form): ...
    def generate_csrf_token(self, csrf_token_field): ...
    def validate_csrf_token(self, form, field) -> None: ...
    def now(self): ...
    @property
    def time_limit(self): ...
    @property
    def session(self): ...
