"""deleting foreign key plan from offer

Revision ID: 37ba4fa0da15
Revises: 44360c73915b
Create Date: 2021-09-12 18:12:22.056164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ba4fa0da15'
down_revision = '44360c73915b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('offer_plan_id_fkey', 'offer', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('offer_plan_id_fkey', 'offer', 'plan', ['plan_id'], ['id'])
    # ### end Alembic commands ###
