"""delete column renewed from plan table

Revision ID: 44360c73915b
Revises: 5ccb2cf7d04c
Create Date: 2021-09-12 16:59:16.993803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44360c73915b'
down_revision = '5ccb2cf7d04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'renewed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('renewed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
