"""add column expiration_relative to table plan

Revision ID: 4fb62f76abb2
Revises: 75b4b273b2f7
Create Date: 2021-08-15 22:15:05.288173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4fb62f76abb2"
down_revision = "75b4b273b2f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plan", sa.Column("expiration_relative", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan", "expiration_relative")
    # ### end Alembic commands ###
