"""changes to company, offer and purchase

Revision ID: 550f512f610a
Revises: 853c1d84bf8e
Create Date: 2021-09-12 18:35:31.339672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550f512f610a'
down_revision = '853c1d84bf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('company', sa.String(), nullable=True))
    op.create_foreign_key(None, 'offer', 'company', ['company'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.drop_column('offer', 'company')
    # ### end Alembic commands ###
