"""add  ccolumn last_certificate_payout to table plan

Revision ID: 652eb046900c
Revises: 3f66e07c61c0
Create Date: 2021-08-15 19:00:42.779090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652eb046900c'
down_revision = '3f66e07c61c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('last_certificate_payout', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'last_certificate_payout')
    # ### end Alembic commands ###
