"""changes to plan table

Revision ID: 6cc564ebe386
Revises: 7198e8c48018
Create Date: 2021-10-20 01:00:11.567667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6cc564ebe386"
down_revision = "7198e8c48018"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("plan", sa.Column("active_days", sa.Integer(), nullable=True))

    op.add_column("plan", sa.Column("payout_count", sa.Integer(), nullable=True))
    op.execute("UPDATE plan SET payout_count = 0")
    op.alter_column("plan", "payout_count", nullable=False)

    op.drop_column("plan", "last_certificate_payout")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan",
        sa.Column(
            "last_certificate_payout",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("plan", "payout_count")
    op.drop_column("plan", "active_days")
    # ### end Alembic commands ###
