"""add column expiration date to table plan

Revision ID: 75b4b273b2f7
Revises: 652eb046900c
Create Date: 2021-08-15 21:50:17.991954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75b4b273b2f7"
down_revision = "652eb046900c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plan", sa.Column("expiration_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan", "expiration_date")
    # ### end Alembic commands ###
