"""create table ExternalMessage

Revision ID: 7915de098c63
Revises: c0dbe17daefe
Create Date: 2021-12-23 22:26:20.076436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7915de098c63"
down_revision = "c0dbe17daefe"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "sent_external_message",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("sent_date", sa.DateTime(), nullable=False),
        sa.Column("sender_adress", sa.String(length=500), nullable=False),
        sa.Column("receiver_adress", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content_html", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("external_message")
    # ### end Alembic commands ###
