"""add price_per_unit to offer table

Revision ID: 8215d518eca9
Revises: 550f512f610a
Create Date: 2021-09-12 18:38:20.464317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8215d518eca9"
down_revision = "550f512f610a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("offer", sa.Column("price_per_unit", sa.Numeric(), nullable=True))
    op.execute("UPDATE offer SET price_per_unit = 0")
    op.alter_column("offer", "price_per_unit", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("offer", "price_per_unit")
    # ### end Alembic commands ###
