"""deleting foreign key plan from purchase

Revision ID: 853c1d84bf8e
Revises: 37ba4fa0da15
Create Date: 2021-09-12 18:13:42.622020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853c1d84bf8e'
down_revision = '37ba4fa0da15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('purchase_plan_id_fkey', 'purchase', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('purchase_plan_id_fkey', 'purchase', 'plan', ['plan_id'], ['id'])
    # ### end Alembic commands ###
