"""add is_available to plan table

Revision ID: 87a9fb39c257
Revises: 803d7861bcbc
Create Date: 2021-11-02 16:09:50.065710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87a9fb39c257"
down_revision = "803d7861bcbc"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("plan", sa.Column("is_available", sa.Boolean(), nullable=True))
    op.execute("UPDATE plan SET is_available = False")
    op.execute("UPDATE plan SET is_available = True WHERE plan.is_active")
    op.alter_column("plan", "is_available", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan", "is_available")
    # ### end Alembic commands ###
