"""Associate Message to UserAction

Revision ID: 932982b81070
Revises: 9f393e810ba4
Create Date: 2022-01-12 10:58:13.879659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932982b81070'
down_revision = '9f393e810ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_action', sa.String(), nullable=True))
    op.create_foreign_key(None, 'message', 'user_action', ['user_action'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'user_action')
    # ### end Alembic commands ###
