"""add column hidden_by_user to plan table

Revision ID: 979e50af653d
Revises: bfe08c4388ae
Create Date: 2021-12-02 21:24:47.737562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "979e50af653d"
down_revision = "bfe08c4388ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plan", sa.Column("hidden_by_user", sa.Boolean(), nullable=True))
    op.execute("UPDATE plan SET hidden_by_user = False")
    op.alter_column("plan", "hidden_by_user", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan", "hidden_by_user")
    # ### end Alembic commands ###
