"""Create proper ActionType table

Revision ID: 9f393e810ba4
Revises: c0dbe17daefe
Create Date: 2022-01-12 10:57:58.521533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f393e810ba4'
down_revision = 'c0dbe17daefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('action_type', sa.Enum('answer_invite', 'answer_cooperation_request', name='useractiontype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('message', 'user_action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_action', postgresql.ENUM('answer_invite', name='useraction'), autoincrement=False, nullable=True))
    op.drop_table('user_action')
    # ### end Alembic commands ###
