"""empty message

Revision ID: b4fea8010fd6
Revises: a8906c6f44bc
Create Date: 2021-08-15 18:32:12.487783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fea8010fd6'
down_revision = 'a8906c6f44bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('balance', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
