"""empty message

Revision ID: be4a64c68826
Revises: d5f7df16a723
Create Date: 2021-09-28 20:07:49.001950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4a64c68826'
down_revision = 'd5f7df16a723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_draft',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_creation_date', sa.DateTime(), nullable=False),
    sa.Column('planner', sa.String(), nullable=False),
    sa.Column('costs_p', sa.Numeric(), nullable=False),
    sa.Column('costs_r', sa.Numeric(), nullable=False),
    sa.Column('costs_a', sa.Numeric(), nullable=False),
    sa.Column('prd_name', sa.String(length=100), nullable=False),
    sa.Column('prd_unit', sa.String(length=100), nullable=False),
    sa.Column('prd_amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('timeframe', sa.Numeric(), nullable=False),
    sa.Column('is_public_service', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['planner'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('plan_social_accounting_fkey', 'plan', type_='foreignkey')
    op.drop_column('plan', 'social_accounting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('social_accounting', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('plan_social_accounting_fkey', 'plan', 'social_accounting', ['social_accounting'], ['id'])
    op.execute('''
        UPDATE plan
        SET social_accounting = (
            SELECT id
            FROM social_accounting
        )
    ''')
    op.alter_column('plan', sa.Column('social_accounting', nullable=False))
    op.drop_table('plan_draft')
    # ### end Alembic commands ###
