"""add registered_on and confirmed_on to member table

Revision ID: c0dbe17daefe
Revises: 979e50af653d
Create Date: 2021-12-21 22:26:43.761009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0dbe17daefe"
down_revision = "979e50af653d"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("member", sa.Column("registered_on", sa.DateTime(), nullable=True))
    op.execute("UPDATE member SET registered_on = '2021-12-21 00:00:00.000'")
    op.alter_column("member", "registered_on", nullable=False)

    op.add_column("member", sa.Column("confirmed_on", sa.DateTime(), nullable=True))
    op.execute("UPDATE member SET confirmed_on = '2021-12-21 01:00:00.000'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("member", "confirmed_on")
    op.drop_column("member", "registered_on")
    # ### end Alembic commands ###
