"""add column activation_date to table plan

Revision ID: d16394e5eb7d
Revises: 4fb62f76abb2
Create Date: 2021-08-15 22:42:12.094201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16394e5eb7d'
down_revision = '4fb62f76abb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('activation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'activation_date')
    # ### end Alembic commands ###
