"""decoupling offers from plans

Revision ID: d9aebe869d40
Revises: 5ccb2cf7d04c
Create Date: 2021-09-13 15:17:01.260253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9aebe869d40'
down_revision = '5ccb2cf7d04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('company', sa.String(), nullable=False))
    op.add_column('offer', sa.Column('price_per_unit', sa.Numeric(), nullable=False))
    op.drop_constraint('offer_plan_id_fkey', 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'company', ['company'], ['id'])
    op.drop_column('plan', 'renewed')
    op.drop_constraint('purchase_plan_id_fkey', 'purchase', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('purchase_plan_id_fkey', 'purchase', 'plan', ['plan_id'], ['id'])
    op.add_column('plan', sa.Column('renewed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key('offer_plan_id_fkey', 'offer', 'plan', ['plan_id'], ['id'])
    op.drop_column('offer', 'price_per_unit')
    op.drop_column('offer', 'company')
    # ### end Alembic commands ###
