"""empty message

Revision ID: d9ddaa4aaac9
Revises: be4a64c68826
Create Date: 2021-10-11 10:41:40.257351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ddaa4aaac9'
down_revision = 'be4a64c68826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_work_invite',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('member', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['company.id'], ),
    sa.ForeignKeyConstraint(['member'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_work_invite')
    # ### end Alembic commands ###
