from typing import Any

def Win32_GetCurrentProcessExplicitAppUserModelID(*args, **kwargs) -> Any: ...
def Win32_GetForegroundWindow(*args, **kwargs) -> Any: ...
def Win32_SetCurrentProcessExplicitAppUserModelID(*args, **kwargs) -> Any: ...
def Win32_SetForegroundWindow(*args, **kwargs) -> Any: ...
def Win32_SetProcessDpiAwareness_max(*args, **kwargs) -> Any: ...
def display_is_valid(*args, **kwargs) -> Any: ...
