def Win32_GetCurrentProcessExplicitAppUserModelID(*args, **kwargs): ...
def Win32_GetForegroundWindow(*args, **kwargs): ...
def Win32_SetCurrentProcessExplicitAppUserModelID(*args, **kwargs): ...
def Win32_SetForegroundWindow(*args, **kwargs): ...
def Win32_SetProcessDpiAwareness_max(*args, **kwargs): ...
def display_is_valid(*args, **kwargs): ...
