def Win32_GetCurrentProcessExplicitAppUserModelID() -> object: ...
def Win32_GetForegroundWindow() -> object: ...
def Win32_SetCurrentProcessExplicitAppUserModelID(*args, **kwargs): ...
def Win32_SetForegroundWindow(hwnd: capsule) -> None: ...
def Win32_SetProcessDpiAwareness_max() -> None: ...
def display_is_valid() -> bool: ...
