from _typeshed import Incomplete

def do_constrained_layout(fig, h_pad, w_pad, hspace: Incomplete | None = ..., wspace: Incomplete | None = ..., rect=..., compress: bool = ...): ...
def make_layoutgrids(fig, layoutgrids, rect=...): ...
def make_layoutgrids_gs(layoutgrids, gs): ...
def check_no_collapsed_axes(layoutgrids, fig): ...
def compress_fixed_aspect(layoutgrids, fig): ...
def get_margin_from_padding(obj, *, w_pad: int = ..., h_pad: int = ..., hspace: int = ..., wspace: int = ...): ...
def make_layout_margins(layoutgrids, fig, renderer, *, w_pad: int = ..., h_pad: int = ..., hspace: int = ..., wspace: int = ...) -> None: ...
def make_margin_suptitles(layoutgrids, fig, renderer, *, w_pad: int = ..., h_pad: int = ...) -> None: ...
def match_submerged_margins(layoutgrids, fig) -> None: ...
def get_cb_parent_spans(cbax): ...
def get_pos_and_bbox(ax, renderer): ...
def reposition_axes(layoutgrids, fig, renderer, *, w_pad: int = ..., h_pad: int = ..., hspace: int = ..., wspace: int = ...) -> None: ...
def reposition_colorbar(layoutgrids, cbax, renderer, *, offset: Incomplete | None = ...): ...
def reset_margins(layoutgrids, fig) -> None: ...
def colorbar_get_pad(layoutgrids, cax): ...
