from _typeshed import Incomplete

def do_constrained_layout(
    fig,
    h_pad,
    w_pad,
    hspace: Incomplete | None = None,
    wspace: Incomplete | None = None,
    rect=(0, 0, 1, 1),
    compress: bool = False,
): ...
def make_layoutgrids(fig, layoutgrids, rect=(0, 0, 1, 1)): ...
def make_layoutgrids_gs(layoutgrids, gs): ...
def check_no_collapsed_axes(layoutgrids, fig): ...
def compress_fixed_aspect(layoutgrids, fig): ...
def get_margin_from_padding(
    obj, *, w_pad: int = 0, h_pad: int = 0, hspace: int = 0, wspace: int = 0
): ...
def make_layout_margins(
    layoutgrids,
    fig,
    renderer,
    *,
    w_pad: int = 0,
    h_pad: int = 0,
    hspace: int = 0,
    wspace: int = 0,
) -> None: ...
def make_margin_suptitles(
    layoutgrids, fig, renderer, *, w_pad: int = 0, h_pad: int = 0
) -> None: ...
def match_submerged_margins(layoutgrids, fig) -> None: ...
def get_cb_parent_spans(cbax): ...
def get_pos_and_bbox(ax, renderer): ...
def reposition_axes(
    layoutgrids,
    fig,
    renderer,
    *,
    w_pad: int = 0,
    h_pad: int = 0,
    hspace: int = 0,
    wspace: int = 0,
) -> None: ...
def reposition_colorbar(
    layoutgrids, cbax, renderer, *, offset: Incomplete | None = None
): ...
def reset_margins(layoutgrids, fig) -> None: ...
def colorbar_get_pad(layoutgrids, cax): ...
