from _typeshed import Incomplete

def kwarg_doc(text): ...

class Substitution:
    params: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def __call__(self, func): ...
    def update(self, *args, **kwargs) -> None: ...

class _ArtistKwdocLoader(dict):
    def __missing__(self, key): ...

class _ArtistPropertiesSubstitution(Substitution):
    params: Incomplete
    def __init__(self) -> None: ...
    def __call__(self, obj): ...

def copy(source): ...

dedent_interpd: Incomplete

interpd: Incomplete
