from _typeshed import Incomplete
from matplotlib.transforms import Bbox as Bbox

class LayoutGrid:
    parent_pos: Incomplete
    parent_inner: Incomplete
    name: Incomplete
    nrows: Incomplete
    ncols: Incomplete
    height_ratios: Incomplete
    width_ratios: Incomplete
    solver: Incomplete
    artists: Incomplete
    children: Incomplete
    margins: Incomplete
    margin_vals: Incomplete
    lefts: Incomplete
    rights: Incomplete
    bottoms: Incomplete
    tops: Incomplete
    h_pad: Incomplete
    w_pad: Incomplete
    def __init__(self, parent: Incomplete | None = ..., parent_pos=..., parent_inner: bool = ..., name: str = ..., ncols: int = ..., nrows: int = ..., h_pad: Incomplete | None = ..., w_pad: Incomplete | None = ..., width_ratios: Incomplete | None = ..., height_ratios: Incomplete | None = ...) -> None: ...
    def reset_margins(self) -> None: ...
    def add_constraints(self, parent) -> None: ...
    def hard_constraints(self) -> None: ...
    def add_child(self, child, i: int = ..., j: int = ...) -> None: ...
    def parent_constraints(self, parent) -> None: ...
    def grid_constraints(self) -> None: ...
    def edit_margin(self, todo, size, cell) -> None: ...
    def edit_margin_min(self, todo, size, cell: int = ...) -> None: ...
    def edit_margins(self, todo, size) -> None: ...
    def edit_all_margins_min(self, todo, size) -> None: ...
    def edit_outer_margin_mins(self, margin, ss) -> None: ...
    def get_margins(self, todo, col): ...
    def get_outer_bbox(self, rows: int = ..., cols: int = ...): ...
    def get_inner_bbox(self, rows: int = ..., cols: int = ...): ...
    def get_bbox_for_cb(self, rows: int = ..., cols: int = ...): ...
    def get_left_margin_bbox(self, rows: int = ..., cols: int = ...): ...
    def get_bottom_margin_bbox(self, rows: int = ..., cols: int = ...): ...
    def get_right_margin_bbox(self, rows: int = ..., cols: int = ...): ...
    def get_top_margin_bbox(self, rows: int = ..., cols: int = ...): ...
    def update_variables(self) -> None: ...

def seq_id(): ...
def plot_children(fig, lg: Incomplete | None = ..., level: int = ...) -> None: ...
