from _typeshed import Incomplete
from matplotlib.transforms import Bbox as Bbox

class LayoutGrid:
    parent_pos: Incomplete
    parent_inner: Incomplete
    name: Incomplete
    nrows: Incomplete
    ncols: Incomplete
    height_ratios: Incomplete
    width_ratios: Incomplete
    solver: Incomplete
    artists: Incomplete
    children: Incomplete
    margins: Incomplete
    margin_vals: Incomplete
    lefts: Incomplete
    rights: Incomplete
    bottoms: Incomplete
    tops: Incomplete
    h_pad: Incomplete
    w_pad: Incomplete
    def __init__(
        self,
        parent: Incomplete | None = None,
        parent_pos=(0, 0),
        parent_inner: bool = False,
        name: str = "",
        ncols: int = 1,
        nrows: int = 1,
        h_pad: Incomplete | None = None,
        w_pad: Incomplete | None = None,
        width_ratios: Incomplete | None = None,
        height_ratios: Incomplete | None = None,
    ) -> None: ...
    def reset_margins(self) -> None: ...
    def add_constraints(self, parent) -> None: ...
    def hard_constraints(self) -> None: ...
    def add_child(self, child, i: int = 0, j: int = 0) -> None: ...
    def parent_constraints(self, parent) -> None: ...
    def grid_constraints(self) -> None: ...
    def edit_margin(self, todo, size, cell) -> None: ...
    def edit_margin_min(self, todo, size, cell: int = 0) -> None: ...
    def edit_margins(self, todo, size) -> None: ...
    def edit_all_margins_min(self, todo, size) -> None: ...
    def edit_outer_margin_mins(self, margin, ss) -> None: ...
    def get_margins(self, todo, col): ...
    def get_outer_bbox(self, rows: int = 0, cols: int = 0): ...
    def get_inner_bbox(self, rows: int = 0, cols: int = 0): ...
    def get_bbox_for_cb(self, rows: int = 0, cols: int = 0): ...
    def get_left_margin_bbox(self, rows: int = 0, cols: int = 0): ...
    def get_bottom_margin_bbox(self, rows: int = 0, cols: int = 0): ...
    def get_right_margin_bbox(self, rows: int = 0, cols: int = 0): ...
    def get_top_margin_bbox(self, rows: int = 0, cols: int = 0): ...
    def update_variables(self) -> None: ...

def seq_id(): ...
def plot_children(fig, lg: Incomplete | None = None, level: int = 0) -> None: ...
