import enum
from . import cbook as cbook
from ._mathtext_data import latex_to_bakoma as latex_to_bakoma, stix_glyph_fixes as stix_glyph_fixes, stix_virtual_fonts as stix_virtual_fonts, tex2uni as tex2uni
from .font_manager import FontProperties as FontProperties, findfont as findfont, get_font as get_font
from .ft2font import FT2Image as FT2Image, KERNING_DEFAULT as KERNING_DEFAULT
from _typeshed import Incomplete
from typing import NamedTuple

def get_unicode_index(symbol, math: bool = ...): ...

class VectorParse(NamedTuple):
    width: Incomplete
    height: Incomplete
    depth: Incomplete
    glyphs: Incomplete
    rects: Incomplete

class RasterParse(NamedTuple):
    ox: Incomplete
    oy: Incomplete
    width: Incomplete
    height: Incomplete
    depth: Incomplete
    image: Incomplete

class Output:
    box: Incomplete
    glyphs: Incomplete
    rects: Incomplete
    def __init__(self, box) -> None: ...
    def to_vector(self): ...
    def to_raster(self): ...

class Fonts:
    default_font_prop: Incomplete
    load_glyph_flags: Incomplete
    def __init__(self, default_font_prop, load_glyph_flags) -> None: ...
    def get_kern(self, font1, fontclass1, sym1, fontsize1, font2, fontclass2, sym2, fontsize2, dpi): ...
    def get_metrics(self, font, font_class, sym, fontsize, dpi): ...
    def render_glyph(self, output, ox, oy, font, font_class, sym, fontsize, dpi) -> None: ...
    def render_rect_filled(self, output, x1, y1, x2, y2) -> None: ...
    def get_xheight(self, font, fontsize, dpi) -> None: ...
    def get_underline_thickness(self, font, fontsize, dpi) -> None: ...
    def get_used_characters(self): ...
    def get_sized_alternatives_for_symbol(self, fontname, sym): ...

class TruetypeFonts(Fonts):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_xheight(self, fontname, fontsize, dpi): ...
    def get_underline_thickness(self, font, fontsize, dpi): ...
    def get_kern(self, font1, fontclass1, sym1, fontsize1, font2, fontclass2, sym2, fontsize2, dpi): ...

class BakomaFonts(TruetypeFonts):
    fontmap: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get_sized_alternatives_for_symbol(self, fontname, sym): ...

class UnicodeFonts(TruetypeFonts):
    fontmap: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get_sized_alternatives_for_symbol(self, fontname, sym): ...

class DejaVuFonts(UnicodeFonts):
    bakoma: Incomplete
    fontmap: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...

class DejaVuSerifFonts(DejaVuFonts): ...
class DejaVuSansFonts(DejaVuFonts): ...

class StixFonts(UnicodeFonts):
    fontmap: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get_sized_alternatives_for_symbol(self, fontname, sym): ...

class StixSansFonts(StixFonts): ...

SHRINK_FACTOR: float
NUM_SIZE_LEVELS: int

class FontConstantsBase:
    script_space: float
    subdrop: float
    sup1: float
    sub1: float
    sub2: float
    delta: float
    delta_slanted: float
    delta_integral: float

class ComputerModernFontConstants(FontConstantsBase):
    script_space: float
    subdrop: float
    sup1: float
    sub1: float
    sub2: float
    delta: float
    delta_slanted: float
    delta_integral: float

class STIXFontConstants(FontConstantsBase):
    script_space: float
    sup1: float
    sub2: float
    delta: float
    delta_slanted: float
    delta_integral: float

class STIXSansFontConstants(FontConstantsBase):
    script_space: float
    sup1: float
    delta_slanted: float
    delta_integral: float

class DejaVuSerifFontConstants(FontConstantsBase): ...
class DejaVuSansFontConstants(FontConstantsBase): ...

class Node:
    size: int
    def __init__(self) -> None: ...
    def get_kerning(self, next): ...
    def shrink(self) -> None: ...
    def render(self, output, x, y) -> None: ...

class Box(Node):
    width: Incomplete
    height: Incomplete
    depth: Incomplete
    def __init__(self, width, height, depth) -> None: ...
    def shrink(self) -> None: ...
    def render(self, output, x1, y1, x2, y2) -> None: ...

class Vbox(Box):
    def __init__(self, height, depth) -> None: ...

class Hbox(Box):
    def __init__(self, width) -> None: ...

class Char(Node):
    c: Incomplete
    fontset: Incomplete
    font: Incomplete
    font_class: Incomplete
    fontsize: Incomplete
    dpi: Incomplete
    def __init__(self, c, state) -> None: ...
    def is_slanted(self): ...
    def get_kerning(self, next): ...
    def render(self, output, x, y) -> None: ...
    def shrink(self) -> None: ...

class Accent(Char):
    def shrink(self) -> None: ...
    def render(self, output, x, y) -> None: ...

class List(Box):
    shift_amount: float
    children: Incomplete
    glue_set: float
    glue_sign: int
    glue_order: int
    def __init__(self, elements) -> None: ...
    def shrink(self) -> None: ...

class Hlist(List):
    def __init__(self, elements, w: float = ..., m: str = ..., do_kern: bool = ...) -> None: ...
    children: Incomplete
    def kern(self) -> None: ...
    height: Incomplete
    depth: Incomplete
    width: Incomplete
    glue_sign: int
    glue_order: int
    glue_ratio: float
    def hpack(self, w: float = ..., m: str = ...) -> None: ...

class Vlist(List):
    def __init__(self, elements, h: float = ..., m: str = ...) -> None: ...
    width: Incomplete
    depth: Incomplete
    height: Incomplete
    glue_sign: int
    glue_order: int
    glue_ratio: float
    def vpack(self, h: float = ..., m: str = ..., l=...) -> None: ...

class Rule(Box):
    fontset: Incomplete
    def __init__(self, width, height, depth, state) -> None: ...
    def render(self, output, x, y, w, h) -> None: ...

class Hrule(Rule):
    def __init__(self, state, thickness: Incomplete | None = ...) -> None: ...

class Vrule(Rule):
    def __init__(self, state) -> None: ...

class _GlueSpec(NamedTuple):
    width: Incomplete
    stretch: Incomplete
    stretch_order: Incomplete
    shrink: Incomplete
    shrink_order: Incomplete

class Glue(Node):
    glue_spec: Incomplete
    def __init__(self, glue_type) -> None: ...
    def shrink(self) -> None: ...

class HCentered(Hlist):
    def __init__(self, elements) -> None: ...

class VCentered(Vlist):
    def __init__(self, elements) -> None: ...

class Kern(Node):
    height: int
    depth: int
    width: Incomplete
    def __init__(self, width) -> None: ...
    def shrink(self) -> None: ...

class AutoHeightChar(Hlist):
    shift_amount: Incomplete
    def __init__(self, c, height, depth, state, always: bool = ..., factor: Incomplete | None = ...) -> None: ...

class AutoWidthChar(Hlist):
    width: Incomplete
    def __init__(self, c, width, state, always: bool = ..., char_class=...) -> None: ...

def ship(box, xy=...): ...
def Error(msg): ...

class ParserState:
    fontset: Incomplete
    font_class: Incomplete
    fontsize: Incomplete
    dpi: Incomplete
    def __init__(self, fontset, font, font_class, fontsize, dpi) -> None: ...
    def copy(self): ...
    @property
    def font(self): ...
    def get_current_underline_thickness(self): ...

def cmd(expr, args): ...

class Parser:
    class _MathStyle(enum.Enum):
        DISPLAYSTYLE: int
        TEXTSTYLE: int
        SCRIPTSTYLE: int
        SCRIPTSCRIPTSTYLE: int
    def __init__(self) -> None: ...
    def parse(self, s, fonts_object, fontsize, dpi): ...
    def get_state(self): ...
    def pop_state(self) -> None: ...
    def push_state(self) -> None: ...
    def main(self, s, loc, toks): ...
    def math_string(self, s, loc, toks): ...
    def math(self, s, loc, toks): ...
    def non_math(self, s, loc, toks): ...
    float_literal: Incomplete
    def space(self, s, loc, toks): ...
    def customspace(self, s, loc, toks): ...
    def symbol(self, s, loc, toks): ...
    def unknown_symbol(self, s, loc, toks) -> None: ...
    def accent(self, s, loc, toks): ...
    def function(self, s, loc, toks): ...
    def operatorname(self, s, loc, toks): ...
    def start_group(self, s, loc, toks): ...
    def group(self, s, loc, toks): ...
    def required_group(self, s, loc, toks): ...
    optional_group = required_group
    def end_group(self, s, loc, toks): ...
    def font(self, s, loc, toks): ...
    def is_overunder(self, nucleus): ...
    def is_dropsub(self, nucleus): ...
    def is_slanted(self, nucleus): ...
    def is_between_brackets(self, s, loc): ...
    def subsuper(self, s, loc, toks): ...
    def style_literal(self, s, loc, toks): ...
    def genfrac(self, s, loc, toks): ...
    def frac(self, s, loc, toks): ...
    def dfrac(self, s, loc, toks): ...
    def binom(self, s, loc, toks): ...
    overset: Incomplete
    underset: Incomplete
    def sqrt(self, s, loc, toks): ...
    def overline(self, s, loc, toks): ...
    def auto_delim(self, s, loc, toks): ...
