from typing import Any

def affine_transform(*args, **kwargs) -> Any: ...
def cleanup_path(*args, **kwargs) -> Any: ...
def clip_path_to_rect(*args, **kwargs) -> Any: ...
def convert_path_to_polygons(*args, **kwargs) -> Any: ...
def convert_to_string(*args, **kwargs) -> Any: ...
def count_bboxes_overlapping_bbox(*args, **kwargs) -> Any: ...
def get_path_collection_extents(*args, **kwargs) -> Any: ...
def is_sorted_and_has_non_nan(*args, **kwargs) -> Any: ...
def path_in_path(*args, **kwargs) -> Any: ...
def path_intersects_path(*args, **kwargs) -> Any: ...
def path_intersects_rectangle(*args, **kwargs) -> Any: ...
def point_in_path(*args, **kwargs) -> Any: ...
def point_in_path_collection(*args, **kwargs) -> Any: ...
def points_in_path(*args, **kwargs) -> Any: ...
def update_path_extents(*args, **kwargs) -> Any: ...
