from _typeshed import Incomplete

class Gcf:
    figs: Incomplete
    @classmethod
    def get_fig_manager(cls, num): ...
    @classmethod
    def destroy(cls, num) -> None: ...
    @classmethod
    def destroy_fig(cls, fig) -> None: ...
    @classmethod
    def destroy_all(cls) -> None: ...
    @classmethod
    def has_fignum(cls, num): ...
    @classmethod
    def get_all_fig_managers(cls): ...
    @classmethod
    def get_num_fig_managers(cls): ...
    @classmethod
    def get_active(cls): ...
    @classmethod
    def set_active(cls, manager) -> None: ...
    @classmethod
    def draw_all(cls, force: bool = ...) -> None: ...
