import abc
from _typeshed import Incomplete
from collections.abc import Generator
from matplotlib import cbook as cbook
from matplotlib._animation_data import DISPLAY_TEMPLATE as DISPLAY_TEMPLATE, INCLUDED_FRAMES as INCLUDED_FRAMES, JS_INCLUDE as JS_INCLUDE, STYLE_INCLUDE as STYLE_INCLUDE

subprocess_creation_flags: Incomplete

def adjusted_figsize(w, h, dpi, n): ...

class MovieWriterRegistry:
    def __init__(self) -> None: ...
    def register(self, name): ...
    def is_available(self, name): ...
    def __iter__(self): ...
    def list(self): ...
    def __getitem__(self, name): ...

writers: Incomplete

class AbstractMovieWriter(abc.ABC, metaclass=abc.ABCMeta):
    fps: Incomplete
    metadata: Incomplete
    codec: Incomplete
    bitrate: Incomplete
    def __init__(self, fps: int = ..., metadata: Incomplete | None = ..., codec: Incomplete | None = ..., bitrate: Incomplete | None = ...) -> None: ...
    outfile: Incomplete
    fig: Incomplete
    dpi: Incomplete
    @abc.abstractmethod
    def setup(self, fig, outfile, dpi: Incomplete | None = ...): ...
    @property
    def frame_size(self): ...
    @abc.abstractmethod
    def grab_frame(self, **savefig_kwargs): ...
    @abc.abstractmethod
    def finish(self): ...
    def saving(self, fig, outfile, dpi, *args, **kwargs) -> Generator[Incomplete, None, None]: ...

class MovieWriter(AbstractMovieWriter):
    supported_formats: Incomplete
    frame_format: Incomplete
    extra_args: Incomplete
    def __init__(self, fps: int = ..., codec: Incomplete | None = ..., bitrate: Incomplete | None = ..., extra_args: Incomplete | None = ..., metadata: Incomplete | None = ...) -> None: ...
    def setup(self, fig, outfile, dpi: Incomplete | None = ...) -> None: ...
    def finish(self) -> None: ...
    def grab_frame(self, **savefig_kwargs) -> None: ...
    @classmethod
    def bin_path(cls): ...
    @classmethod
    def isAvailable(cls): ...

class FileMovieWriter(MovieWriter):
    def __init__(self, *args, **kwargs) -> None: ...
    fig: Incomplete
    outfile: Incomplete
    dpi: Incomplete
    temp_prefix: Incomplete
    fname_format_str: str
    def setup(self, fig, outfile, dpi: Incomplete | None = ..., frame_prefix: Incomplete | None = ...) -> None: ...
    def __del__(self) -> None: ...
    @property
    def frame_format(self): ...
    def grab_frame(self, **savefig_kwargs) -> None: ...
    def finish(self) -> None: ...

class PillowWriter(AbstractMovieWriter):
    @classmethod
    def isAvailable(cls): ...
    def setup(self, fig, outfile, dpi: Incomplete | None = ...) -> None: ...
    def grab_frame(self, **savefig_kwargs) -> None: ...
    def finish(self) -> None: ...

class FFMpegBase:
    codec: str
    @property
    def output_args(self): ...

class FFMpegWriter(FFMpegBase, MovieWriter): ...

class FFMpegFileWriter(FFMpegBase, FileMovieWriter):
    supported_formats: Incomplete

class ImageMagickBase:
    @classmethod
    def bin_path(cls): ...
    @classmethod
    def isAvailable(cls): ...

class ImageMagickWriter(ImageMagickBase, MovieWriter):
    input_names: str

class ImageMagickFileWriter(ImageMagickBase, FileMovieWriter):
    supported_formats: Incomplete
    input_names: Incomplete

class HTMLWriter(FileMovieWriter):
    supported_formats: Incomplete
    @classmethod
    def isAvailable(cls): ...
    embed_frames: Incomplete
    default_mode: Incomplete
    def __init__(self, fps: int = ..., codec: Incomplete | None = ..., bitrate: Incomplete | None = ..., extra_args: Incomplete | None = ..., metadata: Incomplete | None = ..., embed_frames: bool = ..., default_mode: str = ..., embed_limit: Incomplete | None = ...) -> None: ...
    def setup(self, fig, outfile, dpi: Incomplete | None = ..., frame_dir: Incomplete | None = ...) -> None: ...
    def grab_frame(self, **savefig_kwargs): ...
    def finish(self) -> None: ...

class Animation:
    frame_seq: Incomplete
    event_source: Incomplete
    def __init__(self, fig, event_source: Incomplete | None = ..., blit: bool = ...) -> None: ...
    def __del__(self) -> None: ...
    def save(self, filename, writer: Incomplete | None = ..., fps: Incomplete | None = ..., dpi: Incomplete | None = ..., codec: Incomplete | None = ..., bitrate: Incomplete | None = ..., extra_args: Incomplete | None = ..., metadata: Incomplete | None = ..., extra_anim: Incomplete | None = ..., savefig_kwargs: Incomplete | None = ..., *, progress_callback: Incomplete | None = ...): ...
    def new_frame_seq(self): ...
    def new_saved_frame_seq(self): ...
    def to_html5_video(self, embed_limit: Incomplete | None = ...): ...
    def to_jshtml(self, fps: Incomplete | None = ..., embed_frames: bool = ..., default_mode: Incomplete | None = ...): ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...

class TimedAnimation(Animation):
    def __init__(self, fig, interval: int = ..., repeat_delay: int = ..., repeat: bool = ..., event_source: Incomplete | None = ..., *args, **kwargs) -> None: ...
    repeat: Incomplete

class ArtistAnimation(TimedAnimation):
    def __init__(self, fig, artists, *args, **kwargs) -> None: ...

class FuncAnimation(TimedAnimation):
    def __init__(self, fig, func, frames: Incomplete | None = ..., init_func: Incomplete | None = ..., fargs: Incomplete | None = ..., save_count: Incomplete | None = ..., *, cache_frame_data: bool = ..., **kwargs) -> None: ...
    def new_frame_seq(self): ...
    def new_saved_frame_seq(self): ...
    save_count: Incomplete
