import matplotlib.artist as martist
from _typeshed import Incomplete
from matplotlib import cbook as cbook

GRIDLINE_INTERPOLATION_STEPS: int

class Tick(martist.Artist):
    axes: Incomplete
    tick1line: Incomplete
    tick2line: Incomplete
    gridline: Incomplete
    label1: Incomplete
    label2: Incomplete
    def __init__(
        self,
        axes,
        loc,
        *,
        size: Incomplete | None = None,
        width: Incomplete | None = None,
        color: Incomplete | None = None,
        tickdir: Incomplete | None = None,
        pad: Incomplete | None = None,
        labelsize: Incomplete | None = None,
        labelcolor: Incomplete | None = None,
        labelfontfamily: Incomplete | None = None,
        zorder: Incomplete | None = None,
        gridOn: Incomplete | None = None,
        tick1On: bool = True,
        tick2On: bool = True,
        label1On: bool = True,
        label2On: bool = False,
        major: bool = True,
        labelrotation: int = 0,
        grid_color: Incomplete | None = None,
        grid_linestyle: Incomplete | None = None,
        grid_linewidth: Incomplete | None = None,
        grid_alpha: Incomplete | None = None,
        **kwargs,
    ) -> None: ...
    def get_tickdir(self): ...
    def get_tick_padding(self): ...
    def get_children(self): ...
    stale: bool
    def set_clip_path(self, path, transform: Incomplete | None = None) -> None: ...
    def contains(self, mouseevent): ...
    def set_pad(self, val) -> None: ...
    def get_pad(self): ...
    def get_loc(self): ...
    def draw(self, renderer) -> None: ...
    def set_label1(self, s) -> None: ...
    set_label = set_label1
    def set_label2(self, s) -> None: ...
    def set_url(self, url) -> None: ...
    def get_view_interval(self) -> None: ...
    def update_position(self, loc) -> None: ...

class XTick(Tick):
    def __init__(self, *args, **kwargs) -> None: ...
    stale: bool
    def update_position(self, loc) -> None: ...
    def get_view_interval(self): ...

class YTick(Tick):
    def __init__(self, *args, **kwargs) -> None: ...
    stale: bool
    def update_position(self, loc) -> None: ...
    def get_view_interval(self): ...

class Ticker:
    def __init__(self) -> None: ...
    @property
    def locator(self): ...
    @locator.setter
    def locator(self, locator) -> None: ...
    @property
    def formatter(self): ...
    @formatter.setter
    def formatter(self, formatter) -> None: ...

class _LazyTickList:
    def __init__(self, major) -> None: ...
    def __get__(self, instance, owner): ...

class Axis(martist.Artist):
    OFFSETTEXTPAD: int
    isDefault_label: bool
    axes: Incomplete
    major: Incomplete
    minor: Incomplete
    callbacks: Incomplete
    label: Incomplete
    offsetText: Incomplete
    labelpad: Incomplete
    pickradius: Incomplete
    converter: Incomplete
    units: Incomplete
    def __init__(self, axes, *, pickradius: int = 15, clear: bool = True) -> None: ...
    @property
    def isDefault_majloc(self): ...
    @isDefault_majloc.setter
    def isDefault_majloc(self, value) -> None: ...
    @property
    def isDefault_majfmt(self): ...
    @isDefault_majfmt.setter
    def isDefault_majfmt(self, value) -> None: ...
    @property
    def isDefault_minloc(self): ...
    @isDefault_minloc.setter
    def isDefault_minloc(self, value) -> None: ...
    @property
    def isDefault_minfmt(self): ...
    @isDefault_minfmt.setter
    def isDefault_minfmt(self, value) -> None: ...
    majorTicks: Incomplete
    minorTicks: Incomplete
    def get_remove_overlapping_locs(self): ...
    def set_remove_overlapping_locs(self, val) -> None: ...
    remove_overlapping_locs: Incomplete
    stale: bool
    def set_label_coords(self, x, y, transform: Incomplete | None = None) -> None: ...
    def get_transform(self): ...
    def get_scale(self): ...
    def limit_range_for_scale(self, vmin, vmax): ...
    def get_children(self): ...
    def clear(self) -> None: ...
    def reset_ticks(self) -> None: ...
    def minorticks_on(self) -> None: ...
    def minorticks_off(self) -> None: ...
    def set_tick_params(
        self, which: str = "major", reset: bool = False, **kwargs
    ) -> None: ...
    def get_tick_params(self, which: str = "major"): ...
    def set_clip_path(self, path, transform: Incomplete | None = None) -> None: ...
    def get_view_interval(self) -> None: ...
    def set_view_interval(self, vmin, vmax, ignore: bool = False) -> None: ...
    def get_data_interval(self) -> None: ...
    def set_data_interval(self, vmin, vmax, ignore: bool = False) -> None: ...
    def get_inverted(self): ...
    def set_inverted(self, inverted) -> None: ...
    def set_default_intervals(self) -> None: ...
    def get_tightbbox(
        self, renderer: Incomplete | None = None, *, for_layout_only: bool = False
    ): ...
    def get_tick_padding(self): ...
    def draw(self, renderer) -> None: ...
    def get_gridlines(self): ...
    def get_label(self): ...
    def get_offset_text(self): ...
    def get_pickradius(self): ...
    def get_majorticklabels(self): ...
    def get_minorticklabels(self): ...
    def get_ticklabels(self, minor: bool = False, which: Incomplete | None = None): ...
    def get_majorticklines(self): ...
    def get_minorticklines(self): ...
    def get_ticklines(self, minor: bool = False): ...
    def get_majorticklocs(self): ...
    def get_minorticklocs(self): ...
    def get_ticklocs(self, *, minor: bool = False): ...
    def get_ticks_direction(self, minor: bool = False): ...
    def get_label_text(self): ...
    def get_major_locator(self): ...
    def get_minor_locator(self): ...
    def get_major_formatter(self): ...
    def get_minor_formatter(self): ...
    def get_major_ticks(self, numticks: Incomplete | None = None): ...
    def get_minor_ticks(self, numticks: Incomplete | None = None): ...
    def grid(
        self, visible: Incomplete | None = None, which: str = "major", **kwargs
    ) -> None: ...
    def update_units(self, data): ...
    def have_units(self): ...
    def convert_units(self, x): ...
    def set_units(self, u) -> None: ...
    def get_units(self): ...
    def set_label_text(self, label, fontdict: Incomplete | None = None, **kwargs): ...
    def set_major_formatter(self, formatter) -> None: ...
    def set_minor_formatter(self, formatter) -> None: ...
    def set_major_locator(self, locator) -> None: ...
    def set_minor_locator(self, locator) -> None: ...
    def set_pickradius(self, pickradius) -> None: ...
    def set_ticklabels(
        self,
        labels,
        *,
        minor: bool = False,
        fontdict: Incomplete | None = None,
        **kwargs,
    ): ...
    def set_ticks(
        self, ticks, labels: Incomplete | None = None, *, minor: bool = False, **kwargs
    ): ...
    def axis_date(self, tz: Incomplete | None = None) -> None: ...
    def get_tick_space(self) -> None: ...
    def get_label_position(self): ...
    def set_label_position(self, position) -> None: ...
    def get_minpos(self) -> None: ...

class XAxis(Axis):
    axis_name: str
    def __init__(self, *args, **kwargs) -> None: ...
    def contains(self, mouseevent): ...
    label_position: Incomplete
    stale: bool
    def set_label_position(self, position) -> None: ...
    def set_ticks_position(self, position) -> None: ...
    def tick_top(self) -> None: ...
    def tick_bottom(self) -> None: ...
    def get_ticks_position(self): ...
    get_view_interval: Incomplete
    set_view_interval: Incomplete
    get_data_interval: Incomplete
    set_data_interval: Incomplete
    def get_minpos(self): ...
    def set_default_intervals(self) -> None: ...
    def get_tick_space(self): ...

class YAxis(Axis):
    axis_name: str
    def __init__(self, *args, **kwargs) -> None: ...
    def contains(self, mouseevent): ...
    label_position: Incomplete
    stale: bool
    def set_label_position(self, position) -> None: ...
    def set_offset_position(self, position) -> None: ...
    def set_ticks_position(self, position) -> None: ...
    def tick_right(self) -> None: ...
    def tick_left(self) -> None: ...
    def get_ticks_position(self): ...
    get_view_interval: Incomplete
    set_view_interval: Incomplete
    get_data_interval: Incomplete
    set_data_interval: Incomplete
    def get_minpos(self): ...
    def set_default_intervals(self) -> None: ...
    def get_tick_space(self): ...
