from ._color_data import BASE_COLORS as BASE_COLORS, CSS4_COLORS as CSS4_COLORS, TABLEAU_COLORS as TABLEAU_COLORS, XKCD_COLORS as XKCD_COLORS
from _typeshed import Incomplete
from collections.abc import Mapping
from matplotlib import cbook as cbook, scale as scale

class _ColorMapping(dict):
    cache: Incomplete
    def __init__(self, mapping) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...

def get_named_colors_mapping(): ...

class ColorSequenceRegistry(Mapping):
    def __init__(self) -> None: ...
    def __getitem__(self, item): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def register(self, name, color_list) -> None: ...
    def unregister(self, name) -> None: ...

def is_color_like(c): ...
def same_color(c1, c2): ...
def to_rgba(c, alpha: Incomplete | None = ...): ...
def to_rgba_array(c, alpha: Incomplete | None = ...): ...
def to_rgb(c): ...
def to_hex(c, keep_alpha: bool = ...): ...
cnames = CSS4_COLORS
hexColorPattern: Incomplete
rgb2hex = to_hex
hex2color = to_rgb

class ColorConverter:
    colors: Incomplete
    cache: Incomplete
    to_rgb: Incomplete
    to_rgba: Incomplete
    to_rgba_array: Incomplete

colorConverter: Incomplete

class Colormap:
    name: Incomplete
    N: Incomplete
    colorbar_extend: bool
    def __init__(self, name, N: int = ...) -> None: ...
    def __call__(self, X, alpha: Incomplete | None = ..., bytes: bool = ...): ...
    def __copy__(self): ...
    def __eq__(self, other): ...
    def get_bad(self): ...
    def set_bad(self, color: str = ..., alpha: Incomplete | None = ...) -> None: ...
    def get_under(self): ...
    def set_under(self, color: str = ..., alpha: Incomplete | None = ...) -> None: ...
    def get_over(self): ...
    def set_over(self, color: str = ..., alpha: Incomplete | None = ...) -> None: ...
    def set_extremes(self, *, bad: Incomplete | None = ..., under: Incomplete | None = ..., over: Incomplete | None = ...) -> None: ...
    def with_extremes(self, *, bad: Incomplete | None = ..., under: Incomplete | None = ..., over: Incomplete | None = ...): ...
    def is_gray(self): ...
    def resampled(self, lutsize): ...
    def reversed(self, name: Incomplete | None = ...) -> None: ...
    def copy(self): ...

class LinearSegmentedColormap(Colormap):
    monochrome: bool
    def __init__(self, name, segmentdata, N: int = ..., gamma: float = ...) -> None: ...
    def set_gamma(self, gamma) -> None: ...
    @staticmethod
    def from_list(name, colors, N: int = ..., gamma: float = ...): ...
    def resampled(self, lutsize): ...
    def reversed(self, name: Incomplete | None = ...): ...

class ListedColormap(Colormap):
    monochrome: bool
    colors: Incomplete
    def __init__(self, colors, name: str = ..., N: Incomplete | None = ...) -> None: ...
    def resampled(self, lutsize): ...
    def reversed(self, name: Incomplete | None = ...): ...

class Normalize:
    callbacks: Incomplete
    def __init__(self, vmin: Incomplete | None = ..., vmax: Incomplete | None = ..., clip: bool = ...) -> None: ...
    @property
    def vmin(self): ...
    @property
    def vmax(self): ...
    @property
    def clip(self): ...
    @staticmethod
    def process_value(value): ...
    def __call__(self, value, clip: Incomplete | None = ...): ...
    def inverse(self, value): ...
    def autoscale(self, A) -> None: ...
    def autoscale_None(self, A) -> None: ...
    def scaled(self): ...

class TwoSlopeNorm(Normalize):
    def __init__(self, vcenter, vmin: Incomplete | None = ..., vmax: Incomplete | None = ...) -> None: ...
    @property
    def vcenter(self): ...
    vmin: Incomplete
    vmax: Incomplete
    def autoscale_None(self, A) -> None: ...
    def __call__(self, value, clip: Incomplete | None = ...): ...
    def inverse(self, value): ...

class CenteredNorm(Normalize):
    def __init__(self, vcenter: int = ..., halfrange: Incomplete | None = ..., clip: bool = ...) -> None: ...
    def autoscale(self, A) -> None: ...
    def autoscale_None(self, A) -> None: ...
    @property
    def vmin(self): ...
    @property
    def vmax(self): ...
    @property
    def vcenter(self): ...
    @property
    def halfrange(self): ...

def make_norm_from_scale(scale_cls, base_norm_cls: Incomplete | None = ..., *, init: Incomplete | None = ...): ...

class FuncNorm(Normalize): ...

LogNorm: Incomplete

class SymLogNorm(Normalize):
    @property
    def linthresh(self): ...

class AsinhNorm(Normalize):
    @property
    def linear_width(self): ...

class PowerNorm(Normalize):
    gamma: Incomplete
    def __init__(self, gamma, vmin: Incomplete | None = ..., vmax: Incomplete | None = ..., clip: bool = ...) -> None: ...
    def __call__(self, value, clip: Incomplete | None = ...): ...
    def inverse(self, value): ...

class BoundaryNorm(Normalize):
    boundaries: Incomplete
    N: Incomplete
    Ncmap: Incomplete
    extend: Incomplete
    def __init__(self, boundaries, ncolors, clip: bool = ..., *, extend: str = ...) -> None: ...
    def __call__(self, value, clip: Incomplete | None = ...): ...
    def inverse(self, value) -> None: ...

class NoNorm(Normalize):
    def __call__(self, value, clip: Incomplete | None = ...): ...
    def inverse(self, value): ...

def rgb_to_hsv(arr): ...
def hsv_to_rgb(hsv): ...

class LightSource:
    azdeg: Incomplete
    altdeg: Incomplete
    hsv_min_val: Incomplete
    hsv_max_val: Incomplete
    hsv_min_sat: Incomplete
    hsv_max_sat: Incomplete
    def __init__(self, azdeg: int = ..., altdeg: int = ..., hsv_min_val: int = ..., hsv_max_val: int = ..., hsv_min_sat: int = ..., hsv_max_sat: int = ...) -> None: ...
    @property
    def direction(self): ...
    def hillshade(self, elevation, vert_exag: int = ..., dx: int = ..., dy: int = ..., fraction: float = ...): ...
    def shade_normals(self, normals, fraction: float = ...): ...
    def shade(self, data, cmap, norm: Incomplete | None = ..., blend_mode: str = ..., vmin: Incomplete | None = ..., vmax: Incomplete | None = ..., vert_exag: int = ..., dx: int = ..., dy: int = ..., fraction: int = ..., **kwargs): ...
    def shade_rgb(self, rgb, elevation, fraction: float = ..., blend_mode: str = ..., vert_exag: int = ..., dx: int = ..., dy: int = ..., **kwargs): ...
    def blend_hsv(self, rgb, intensity, hsv_max_sat: Incomplete | None = ..., hsv_max_val: Incomplete | None = ..., hsv_min_val: Incomplete | None = ..., hsv_min_sat: Incomplete | None = ...): ...
    def blend_soft_light(self, rgb, intensity): ...
    def blend_overlay(self, rgb, intensity): ...

def from_levels_and_colors(levels, colors, extend: str = ...): ...
