from _typeshed import Incomplete
from dateutil.relativedelta import relativedelta as relativedelta
from dateutil.rrule import DAILY as DAILY, FR as FR, HOURLY as HOURLY, MINUTELY as MINUTELY, MO as MO, MONTHLY as MONTHLY, SA as SA, SECONDLY as SECONDLY, SU as SU, TH as TH, TU as TU, WE as WE, WEEKLY as WEEKLY, YEARLY as YEARLY, rrule as rrule
from matplotlib import ticker, units

class __getattr__:
    JULIAN_OFFSET: Incomplete

MICROSECONDLY: Incomplete

def set_epoch(epoch) -> None: ...
def get_epoch(): ...
def datestr2num(d, default: Incomplete | None = ...): ...
def date2num(d): ...
def num2date(x, tz: Incomplete | None = ...): ...
def num2timedelta(x): ...
def drange(dstart, dend, delta): ...

class DateFormatter(ticker.Formatter):
    tz: Incomplete
    fmt: Incomplete
    def __init__(self, fmt, tz: Incomplete | None = ..., *, usetex: Incomplete | None = ...) -> None: ...
    def __call__(self, x, pos: int = ...): ...
    def set_tzinfo(self, tz) -> None: ...

class ConciseDateFormatter(ticker.Formatter):
    defaultfmt: str
    formats: Incomplete
    zero_formats: Incomplete
    offset_formats: Incomplete
    offset_string: str
    show_offset: Incomplete
    def __init__(self, locator, tz: Incomplete | None = ..., formats: Incomplete | None = ..., offset_formats: Incomplete | None = ..., zero_formats: Incomplete | None = ..., show_offset: bool = ..., *, usetex: Incomplete | None = ...) -> None: ...
    def __call__(self, x, pos: Incomplete | None = ...): ...
    def format_ticks(self, values): ...
    def get_offset(self): ...
    def format_data_short(self, value): ...

class AutoDateFormatter(ticker.Formatter):
    defaultfmt: Incomplete
    scaled: Incomplete
    def __init__(self, locator, tz: Incomplete | None = ..., defaultfmt: str = ..., *, usetex: Incomplete | None = ...) -> None: ...
    def __call__(self, x, pos: Incomplete | None = ...): ...

class rrulewrapper:
    def __init__(self, freq, tzinfo: Incomplete | None = ..., **kwargs) -> None: ...
    def set(self, **kwargs) -> None: ...
    def __getattr__(self, name): ...

class DateLocator(ticker.Locator):
    hms0d: Incomplete
    tz: Incomplete
    def __init__(self, tz: Incomplete | None = ...) -> None: ...
    def set_tzinfo(self, tz) -> None: ...
    def datalim_to_dt(self): ...
    def viewlim_to_dt(self): ...
    def nonsingular(self, vmin, vmax): ...

class RRuleLocator(DateLocator):
    rule: Incomplete
    def __init__(self, o, tz: Incomplete | None = ...) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin, vmax): ...
    @staticmethod
    def get_unit_generic(freq): ...

class AutoDateLocator(DateLocator):
    minticks: Incomplete
    maxticks: Incomplete
    interval_multiples: Incomplete
    intervald: Incomplete
    def __init__(self, tz: Incomplete | None = ..., minticks: int = ..., maxticks: Incomplete | None = ..., interval_multiples: bool = ...) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin, vmax): ...
    def nonsingular(self, vmin, vmax): ...
    def get_locator(self, dmin, dmax): ...

class YearLocator(RRuleLocator):
    base: Incomplete
    def __init__(self, base: int = ..., month: int = ..., day: int = ..., tz: Incomplete | None = ...) -> None: ...

class MonthLocator(RRuleLocator):
    def __init__(self, bymonth: Incomplete | None = ..., bymonthday: int = ..., interval: int = ..., tz: Incomplete | None = ...) -> None: ...

class WeekdayLocator(RRuleLocator):
    def __init__(self, byweekday: int = ..., interval: int = ..., tz: Incomplete | None = ...) -> None: ...

class DayLocator(RRuleLocator):
    def __init__(self, bymonthday: Incomplete | None = ..., interval: int = ..., tz: Incomplete | None = ...) -> None: ...

class HourLocator(RRuleLocator):
    def __init__(self, byhour: Incomplete | None = ..., interval: int = ..., tz: Incomplete | None = ...) -> None: ...

class MinuteLocator(RRuleLocator):
    def __init__(self, byminute: Incomplete | None = ..., interval: int = ..., tz: Incomplete | None = ...) -> None: ...

class SecondLocator(RRuleLocator):
    def __init__(self, bysecond: Incomplete | None = ..., interval: int = ..., tz: Incomplete | None = ...) -> None: ...

class MicrosecondLocator(DateLocator):
    def __init__(self, interval: int = ..., tz: Incomplete | None = ...) -> None: ...
    def set_axis(self, axis): ...
    def __call__(self): ...
    def tick_values(self, vmin, vmax): ...

class DateConverter(units.ConversionInterface):
    def __init__(self, *, interval_multiples: bool = ...) -> None: ...
    def axisinfo(self, unit, axis): ...
    @staticmethod
    def convert(value, unit, axis): ...
    @staticmethod
    def default_units(x, axis): ...

class ConciseDateConverter(DateConverter):
    def __init__(self, formats: Incomplete | None = ..., zero_formats: Incomplete | None = ..., offset_formats: Incomplete | None = ..., show_offset: bool = ..., *, interval_multiples: bool = ...) -> None: ...
    def axisinfo(self, unit, axis): ...

class _SwitchableDateConverter:
    def axisinfo(self, *args, **kwargs): ...
    def default_units(self, *args, **kwargs): ...
    def convert(self, *args, **kwargs): ...
