import matplotlib.artist as martist
import matplotlib.text as mtext
from _typeshed import Incomplete
from matplotlib.font_manager import FontProperties as FontProperties
from matplotlib.image import BboxImage as BboxImage
from matplotlib.patches import FancyArrowPatch as FancyArrowPatch
from matplotlib.patches import FancyBboxPatch as FancyBboxPatch
from matplotlib.transforms import Bbox as Bbox
from matplotlib.transforms import BboxBase as BboxBase
from matplotlib.transforms import TransformedBbox as TransformedBbox

DEBUG: bool

def bbox_artist(*args, **kwargs) -> None: ...

class OffsetBox(martist.Artist):
    def __init__(self, *args, **kwargs) -> None: ...
    def set_figure(self, fig) -> None: ...
    @martist.Artist.axes.setter
    def axes(self, ax) -> None: ...
    def contains(self, mouseevent): ...
    stale: bool
    def set_offset(self, xy) -> None: ...
    def get_offset(self, bbox, renderer): ...
    width: Incomplete
    def set_width(self, width) -> None: ...
    height: Incomplete
    def set_height(self, height) -> None: ...
    def get_visible_children(self): ...
    def get_children(self): ...
    def get_bbox(self, renderer): ...
    def get_extent_offsets(self, renderer): ...
    def get_extent(self, renderer): ...
    def get_window_extent(self, renderer: Incomplete | None = None): ...
    def draw(self, renderer) -> None: ...

class PackerBase(OffsetBox):
    height: Incomplete
    width: Incomplete
    sep: Incomplete
    pad: Incomplete
    mode: Incomplete
    align: Incomplete
    def __init__(
        self,
        pad: float = 0.0,
        sep: float = 0.0,
        width: Incomplete | None = None,
        height: Incomplete | None = None,
        align: str = "baseline",
        mode: str = "fixed",
        children: Incomplete | None = None,
    ) -> None: ...

class VPacker(PackerBase): ...
class HPacker(PackerBase): ...

class PaddedBox(OffsetBox):
    pad: Incomplete
    patch: Incomplete
    def __init__(
        self,
        child,
        pad: float = 0.0,
        *,
        draw_frame: bool = False,
        patch_attrs: Incomplete | None = None,
    ) -> None: ...
    stale: bool
    def draw(self, renderer) -> None: ...
    def update_frame(self, bbox, fontsize: Incomplete | None = None) -> None: ...
    def draw_frame(self, renderer) -> None: ...

class DrawingArea(OffsetBox):
    width: Incomplete
    height: Incomplete
    xdescent: Incomplete
    ydescent: Incomplete
    offset_transform: Incomplete
    dpi_transform: Incomplete
    def __init__(
        self,
        width,
        height,
        xdescent: float = 0.0,
        ydescent: float = 0.0,
        clip: bool = False,
    ) -> None: ...
    @property
    def clip_children(self): ...
    stale: bool
    @clip_children.setter
    def clip_children(self, val) -> None: ...
    def get_transform(self): ...
    def set_transform(self, t) -> None: ...
    def set_offset(self, xy) -> None: ...
    def get_offset(self): ...
    def get_bbox(self, renderer): ...
    def add_artist(self, a) -> None: ...
    def draw(self, renderer) -> None: ...

class TextArea(OffsetBox):
    offset_transform: Incomplete
    def __init__(
        self, s, *, textprops: Incomplete | None = None, multilinebaseline: bool = False
    ) -> None: ...
    stale: bool
    def set_text(self, s) -> None: ...
    def get_text(self): ...
    def set_multilinebaseline(self, t) -> None: ...
    def get_multilinebaseline(self): ...
    def set_transform(self, t) -> None: ...
    def set_offset(self, xy) -> None: ...
    def get_offset(self): ...
    def get_bbox(self, renderer): ...
    def draw(self, renderer) -> None: ...

class AuxTransformBox(OffsetBox):
    aux_transform: Incomplete
    offset_transform: Incomplete
    ref_offset_transform: Incomplete
    def __init__(self, aux_transform) -> None: ...
    stale: bool
    def add_artist(self, a) -> None: ...
    def get_transform(self): ...
    def set_transform(self, t) -> None: ...
    def set_offset(self, xy) -> None: ...
    def get_offset(self): ...
    def get_bbox(self, renderer): ...
    def draw(self, renderer) -> None: ...

class AnchoredOffsetbox(OffsetBox):
    zorder: int
    codes: Incomplete
    loc: Incomplete
    borderpad: Incomplete
    pad: Incomplete
    prop: Incomplete
    patch: Incomplete
    def __init__(
        self,
        loc,
        *,
        pad: float = 0.4,
        borderpad: float = 0.5,
        child: Incomplete | None = None,
        prop: Incomplete | None = None,
        frameon: bool = True,
        bbox_to_anchor: Incomplete | None = None,
        bbox_transform: Incomplete | None = None,
        **kwargs,
    ) -> None: ...
    stale: bool
    def set_child(self, child) -> None: ...
    def get_child(self): ...
    def get_children(self): ...
    def get_bbox(self, renderer): ...
    def get_bbox_to_anchor(self): ...
    def set_bbox_to_anchor(self, bbox, transform: Incomplete | None = None) -> None: ...
    def get_offset(self, bbox, renderer): ...
    def update_frame(self, bbox, fontsize: Incomplete | None = None) -> None: ...
    def draw(self, renderer) -> None: ...

class AnchoredText(AnchoredOffsetbox):
    txt: Incomplete
    def __init__(
        self,
        s,
        loc,
        *,
        pad: float = 0.4,
        borderpad: float = 0.5,
        prop: Incomplete | None = None,
        **kwargs,
    ) -> None: ...

class OffsetImage(OffsetBox):
    image: Incomplete
    def __init__(
        self,
        arr,
        *,
        zoom: int = 1,
        cmap: Incomplete | None = None,
        norm: Incomplete | None = None,
        interpolation: Incomplete | None = None,
        origin: Incomplete | None = None,
        filternorm: bool = True,
        filterrad: float = 4.0,
        resample: bool = False,
        dpi_cor: bool = True,
        **kwargs,
    ) -> None: ...
    stale: bool
    def set_data(self, arr) -> None: ...
    def get_data(self): ...
    def set_zoom(self, zoom) -> None: ...
    def get_zoom(self): ...
    def get_offset(self): ...
    def get_children(self): ...
    def get_bbox(self, renderer): ...
    def draw(self, renderer) -> None: ...

class AnnotationBbox(martist.Artist, mtext._AnnotationBase):
    zorder: int
    offsetbox: Incomplete
    arrowprops: Incomplete
    xybox: Incomplete
    boxcoords: Incomplete
    arrow_patch: Incomplete
    patch: Incomplete
    def __init__(
        self,
        offsetbox,
        xy,
        xybox: Incomplete | None = None,
        xycoords: str = "data",
        boxcoords: Incomplete | None = None,
        *,
        frameon: bool = True,
        pad: float = 0.4,
        annotation_clip: Incomplete | None = None,
        box_alignment=(0.5, 0.5),
        bboxprops: Incomplete | None = None,
        arrowprops: Incomplete | None = None,
        fontsize: Incomplete | None = None,
        **kwargs,
    ) -> None: ...
    @property
    def xyann(self): ...
    stale: bool
    @xyann.setter
    def xyann(self, xyann) -> None: ...
    @property
    def anncoords(self): ...
    @anncoords.setter
    def anncoords(self, coords) -> None: ...
    def contains(self, mouseevent): ...
    def get_children(self): ...
    def set_figure(self, fig) -> None: ...
    prop: Incomplete
    def set_fontsize(self, s: Incomplete | None = None) -> None: ...
    def get_fontsize(self): ...
    def get_window_extent(self, renderer: Incomplete | None = None): ...
    def get_tightbbox(self, renderer: Incomplete | None = None): ...
    def update_positions(self, renderer) -> None: ...
    def draw(self, renderer) -> None: ...

class DraggableBase:
    ref_artist: Incomplete
    got_artist: bool
    def __init__(self, ref_artist, use_blit: bool = False) -> None: ...
    canvas: Incomplete
    cids: Incomplete
    def on_motion(self, evt) -> None: ...
    mouse_x: Incomplete
    mouse_y: Incomplete
    background: Incomplete
    def on_pick(self, evt) -> None: ...
    def on_release(self, event) -> None: ...
    def disconnect(self) -> None: ...
    def save_offset(self) -> None: ...
    def update_offset(self, dx, dy) -> None: ...
    def finalize_offset(self) -> None: ...

class DraggableOffsetBox(DraggableBase):
    offsetbox: Incomplete
    def __init__(self, ref_artist, offsetbox, use_blit: bool = False) -> None: ...
    def save_offset(self) -> None: ...
    def update_offset(self, dx, dy) -> None: ...
    def get_loc_in_canvas(self): ...

class DraggableAnnotation(DraggableBase):
    annotation: Incomplete
    def __init__(self, annotation, use_blit: bool = False) -> None: ...
    def save_offset(self) -> None: ...
    def update_offset(self, dx, dy) -> None: ...
