from _typeshed import Incomplete
from matplotlib import cbook as cbook, dviread as dviread

class TexManager:
    texcache: Incomplete
    def __new__(cls): ...
    def get_font_config(self): ...
    @classmethod
    def get_basefile(cls, tex, fontsize, dpi: Incomplete | None = ...): ...
    @classmethod
    def get_font_preamble(cls): ...
    @classmethod
    def get_custom_preamble(cls): ...
    @classmethod
    def make_tex(cls, tex, fontsize): ...
    @classmethod
    def make_dvi(cls, tex, fontsize): ...
    @classmethod
    def make_png(cls, tex, fontsize, dpi): ...
    @classmethod
    def get_grey(cls, tex, fontsize: Incomplete | None = ..., dpi: Incomplete | None = ...): ...
    @classmethod
    def get_rgba(cls, tex, fontsize: Incomplete | None = ..., dpi: Incomplete | None = ..., rgb=...): ...
    @classmethod
    def get_text_width_height_descent(cls, tex, fontsize, renderer: Incomplete | None = ...): ...
