from _typeshed import Incomplete

class _DummyAxis:
    __name__: str
    dataLim: Incomplete
    viewLim: Incomplete
    def __init__(self, minpos: int = ...) -> None: ...
    def get_view_interval(self): ...
    def set_view_interval(self, vmin, vmax) -> None: ...
    def get_minpos(self): ...
    def get_data_interval(self): ...
    def set_data_interval(self, vmin, vmax) -> None: ...
    def get_tick_space(self): ...

class TickHelper:
    axis: Incomplete
    def set_axis(self, axis) -> None: ...
    def create_dummy_axis(self, **kwargs) -> None: ...

class Formatter(TickHelper):
    locs: Incomplete
    def __call__(self, x, pos: Incomplete | None = ...) -> None: ...
    def format_ticks(self, values): ...
    def format_data(self, value): ...
    def format_data_short(self, value): ...
    def get_offset(self): ...
    def set_locs(self, locs) -> None: ...
    @staticmethod
    def fix_minus(s): ...

class NullFormatter(Formatter):
    def __call__(self, x, pos: Incomplete | None = ...): ...

class FixedFormatter(Formatter):
    seq: Incomplete
    offset_string: str
    def __init__(self, seq) -> None: ...
    def __call__(self, x, pos: Incomplete | None = ...): ...
    def get_offset(self): ...
    def set_offset_string(self, ofs) -> None: ...

class FuncFormatter(Formatter):
    func: Incomplete
    offset_string: str
    def __init__(self, func) -> None: ...
    def __call__(self, x, pos: Incomplete | None = ...): ...
    def get_offset(self): ...
    def set_offset_string(self, ofs) -> None: ...

class FormatStrFormatter(Formatter):
    fmt: Incomplete
    def __init__(self, fmt) -> None: ...
    def __call__(self, x, pos: Incomplete | None = ...): ...

class StrMethodFormatter(Formatter):
    fmt: Incomplete
    def __init__(self, fmt) -> None: ...
    def __call__(self, x, pos: Incomplete | None = ...): ...

class ScalarFormatter(Formatter):
    orderOfMagnitude: int
    format: str
    def __init__(self, useOffset: Incomplete | None = ..., useMathText: Incomplete | None = ..., useLocale: Incomplete | None = ...) -> None: ...
    def get_useOffset(self): ...
    offset: int
    def set_useOffset(self, val) -> None: ...
    useOffset: Incomplete
    def get_useLocale(self): ...
    def set_useLocale(self, val) -> None: ...
    useLocale: Incomplete
    def get_useMathText(self): ...
    def set_useMathText(self, val) -> None: ...
    useMathText: Incomplete
    def __call__(self, x, pos: Incomplete | None = ...): ...
    def set_scientific(self, b) -> None: ...
    def set_powerlimits(self, lims) -> None: ...
    def format_data_short(self, value): ...
    def format_data(self, value): ...
    def get_offset(self): ...
    locs: Incomplete
    def set_locs(self, locs) -> None: ...

class LogFormatter(Formatter):
    minor_thresholds: Incomplete
    def __init__(self, base: float = ..., labelOnlyBase: bool = ..., minor_thresholds: Incomplete | None = ..., linthresh: Incomplete | None = ...) -> None: ...
    def base(self, base) -> None: ...
    def set_base(self, base) -> None: ...
    def label_minor(self, labelOnlyBase) -> None: ...
    labelOnlyBase: Incomplete
    def set_label_minor(self, labelOnlyBase) -> None: ...
    def set_locs(self, locs: Incomplete | None = ...) -> None: ...
    def __call__(self, x, pos: Incomplete | None = ...): ...
    def format_data(self, value): ...
    def format_data_short(self, value): ...

class LogFormatterExponent(LogFormatter): ...

class LogFormatterMathtext(LogFormatter):
    def __call__(self, x, pos: Incomplete | None = ...): ...

class LogFormatterSciNotation(LogFormatterMathtext): ...

class LogitFormatter(Formatter):
    def __init__(self, *, use_overline: bool = ..., one_half: str = ..., minor: bool = ..., minor_threshold: int = ..., minor_number: int = ...) -> None: ...
    def use_overline(self, use_overline) -> None: ...
    def set_one_half(self, one_half) -> None: ...
    def set_minor_threshold(self, minor_threshold) -> None: ...
    def set_minor_number(self, minor_number) -> None: ...
    locs: Incomplete
    def set_locs(self, locs): ...
    def __call__(self, x, pos: Incomplete | None = ...): ...
    def format_data_short(self, value): ...

class EngFormatter(Formatter):
    ENG_PREFIXES: Incomplete
    unit: Incomplete
    places: Incomplete
    sep: Incomplete
    def __init__(self, unit: str = ..., places: Incomplete | None = ..., sep: str = ..., *, usetex: Incomplete | None = ..., useMathText: Incomplete | None = ...) -> None: ...
    def get_usetex(self): ...
    def set_usetex(self, val) -> None: ...
    usetex: Incomplete
    def get_useMathText(self): ...
    def set_useMathText(self, val) -> None: ...
    useMathText: Incomplete
    def __call__(self, x, pos: Incomplete | None = ...): ...
    def format_eng(self, num): ...

class PercentFormatter(Formatter):
    xmax: Incomplete
    decimals: Incomplete
    def __init__(self, xmax: int = ..., decimals: Incomplete | None = ..., symbol: str = ..., is_latex: bool = ...) -> None: ...
    def __call__(self, x, pos: Incomplete | None = ...): ...
    def format_pct(self, x, display_range): ...
    def convert_to_pct(self, x): ...
    @property
    def symbol(self): ...

class Locator(TickHelper):
    MAXTICKS: int
    def tick_values(self, vmin, vmax) -> None: ...
    def set_params(self, **kwargs) -> None: ...
    def __call__(self) -> None: ...
    def raise_if_exceeds(self, locs): ...
    def nonsingular(self, v0, v1): ...
    def view_limits(self, vmin, vmax): ...

class IndexLocator(Locator):
    offset: Incomplete
    def __init__(self, base, offset) -> None: ...
    def set_params(self, base: Incomplete | None = ..., offset: Incomplete | None = ...) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin, vmax): ...

class FixedLocator(Locator):
    locs: Incomplete
    nbins: Incomplete
    def __init__(self, locs, nbins: Incomplete | None = ...) -> None: ...
    def set_params(self, nbins: Incomplete | None = ...) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin, vmax): ...

class NullLocator(Locator):
    def __call__(self): ...
    def tick_values(self, vmin, vmax): ...

class LinearLocator(Locator):
    presets: Incomplete
    def __init__(self, numticks: Incomplete | None = ..., presets: Incomplete | None = ...) -> None: ...
    @property
    def numticks(self): ...
    def set_params(self, numticks: Incomplete | None = ..., presets: Incomplete | None = ...) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin, vmax): ...
    def view_limits(self, vmin, vmax): ...

class MultipleLocator(Locator):
    def __init__(self, base: float = ...) -> None: ...
    def set_params(self, base) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin, vmax): ...
    def view_limits(self, dmin, dmax): ...

class _Edge_integer:
    step: Incomplete
    def __init__(self, step, offset) -> None: ...
    def closeto(self, ms, edge): ...
    def le(self, x): ...
    def ge(self, x): ...

class MaxNLocator(Locator):
    default_params: Incomplete
    def __init__(self, nbins: Incomplete | None = ..., **kwargs) -> None: ...
    def set_params(self, **kwargs) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin, vmax): ...
    def view_limits(self, dmin, dmax): ...

class LogLocator(Locator):
    numdecs: Incomplete
    numticks: Incomplete
    def __init__(self, base: float = ..., subs=..., numdecs: int = ..., numticks: Incomplete | None = ...) -> None: ...
    def set_params(self, base: Incomplete | None = ..., subs: Incomplete | None = ..., numdecs: Incomplete | None = ..., numticks: Incomplete | None = ...) -> None: ...
    def base(self, base) -> None: ...
    def subs(self, subs) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin, vmax): ...
    def view_limits(self, vmin, vmax): ...
    def nonsingular(self, vmin, vmax): ...

class SymmetricalLogLocator(Locator):
    numticks: int
    def __init__(self, transform: Incomplete | None = ..., subs: Incomplete | None = ..., linthresh: Incomplete | None = ..., base: Incomplete | None = ...) -> None: ...
    def set_params(self, subs: Incomplete | None = ..., numticks: Incomplete | None = ...) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin, vmax): ...
    def view_limits(self, vmin, vmax): ...

class AsinhLocator(Locator):
    linear_width: Incomplete
    numticks: Incomplete
    symthresh: Incomplete
    base: Incomplete
    subs: Incomplete
    def __init__(self, linear_width, numticks: int = ..., symthresh: float = ..., base: int = ..., subs: Incomplete | None = ...) -> None: ...
    def set_params(self, numticks: Incomplete | None = ..., symthresh: Incomplete | None = ..., base: Incomplete | None = ..., subs: Incomplete | None = ...) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin, vmax): ...

class LogitLocator(MaxNLocator):
    def __init__(self, minor: bool = ..., *, nbins: str = ...) -> None: ...
    def set_params(self, minor: Incomplete | None = ..., **kwargs) -> None: ...
    @property
    def minor(self): ...
    def tick_values(self, vmin, vmax): ...
    def nonsingular(self, vmin, vmax): ...

class AutoLocator(MaxNLocator):
    def __init__(self) -> None: ...

class AutoMinorLocator(Locator):
    ndivs: Incomplete
    def __init__(self, n: Incomplete | None = ...) -> None: ...
    def __call__(self): ...
    def tick_values(self, vmin, vmax) -> None: ...
