from datetime import date
from typing import Iterator

class Calendar:
    def day_interval(self, *, since: date, until: date) -> DateSpan: ...

class DateSpan:
    since: date
    until: date
    def __contains__(self, element: date) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[date]: ...
    def __init__(self, since, until) -> None: ...
