from _typeshed import Incomplete
from flask import Response as FlaskResponse

from .dependency_injector import DependencyInjector as DependencyInjector
from .response import HttpResponse as HttpResponse

logger: Incomplete
auth: Incomplete
flask_profiler: Incomplete

def render_response(response: HttpResponse) -> FlaskResponse: ...
def verify_password(username: str, password: str) -> bool: ...
def summary() -> FlaskResponse: ...
def details() -> FlaskResponse: ...
def route_overview(route_name: str) -> FlaskResponse: ...
def x_robots_tag_header(response: FlaskResponse) -> FlaskResponse: ...
