from typing import Any, Dict, Protocol

class HttpRequest(Protocol):
    def get_arguments(self) -> Dict[str, str]: ...
    def path_arguments(self) -> Dict[str, Any]: ...

class WrappedRequest:
    def get_arguments(self) -> Dict[str, str]: ...
    def path_arguments(self) -> Dict[str, Any]: ...
