from _typeshed import Incomplete

COOKIE_NAME: str
COOKIE_DURATION: Incomplete
COOKIE_SECURE: bool
COOKIE_HTTPONLY: bool
COOKIE_SAMESITE: Incomplete
LOGIN_MESSAGE: str
LOGIN_MESSAGE_CATEGORY: str
REFRESH_MESSAGE: str
REFRESH_MESSAGE_CATEGORY: str
ID_ATTRIBUTE: str
AUTH_HEADER_NAME: str
SESSION_KEYS: Incomplete
EXEMPT_METHODS: Incomplete
USE_SESSION_FOR_NEXT: bool
