from _typeshed import Incomplete

from .config import COOKIE_NAME as COOKIE_NAME
from .config import EXEMPT_METHODS as EXEMPT_METHODS
from .signals import user_logged_in as user_logged_in
from .signals import user_logged_out as user_logged_out
from .signals import user_login_confirmed as user_login_confirmed

current_user: Incomplete

def encode_cookie(payload, key=None): ...
def decode_cookie(cookie, key=None): ...
def make_next_param(login_url, current_url): ...
def expand_login_view(login_view): ...
def login_url(login_view, next_url=None, next_field: str = "next"): ...
def login_fresh(): ...
def login_remembered(): ...
def login_user(
    user, remember: bool = False, duration=None, force: bool = False, fresh: bool = True
): ...
def logout_user(): ...
def confirm_login() -> None: ...
def login_required(func): ...
def fresh_login_required(func): ...
def set_login_view(login_view, blueprint=None) -> None: ...
