from .config import COOKIE_NAME as COOKIE_NAME, EXEMPT_METHODS as EXEMPT_METHODS
from .signals import user_logged_in as user_logged_in, user_logged_out as user_logged_out, user_login_confirmed as user_login_confirmed
from _typeshed import Incomplete

current_user: Incomplete

def encode_cookie(payload, key: Incomplete | None = ...): ...
def decode_cookie(cookie, key: Incomplete | None = ...): ...
def make_next_param(login_url, current_url): ...
def expand_login_view(login_view): ...
def login_url(login_view, next_url: Incomplete | None = ..., next_field: str = ...): ...
def login_fresh(): ...
def login_remembered(): ...
def login_user(user, remember: bool = ..., duration: Incomplete | None = ..., force: bool = ..., fresh: bool = ...): ...
def logout_user(): ...
def confirm_login() -> None: ...
def login_required(func): ...
def fresh_login_required(func): ...
def set_login_view(login_view, blueprint: Incomplete | None = ...) -> None: ...
