from typing import Any, Dict

class Namespace:
    def __init__(self, name: str, description: str) -> None: ...
    def add_resource(self, resource, *urls, **kwargs): ...
    def route(self, *urls, **kwargs): ...
    def add_model(self, name: str, definition: Any) -> Any: ...
    def model(self, name: str, model: Dict[str, Any]) -> Any: ...
    def marshal_with(self, model: Any): ...

class Api:
    def __init__(self, app, title, version, description, doc) -> None: ...
    def add_namespace(self, ns, path=None): ...

class Resource: ...
class Model: ...
