from _typeshed import Incomplete
from flask import Blueprint

class Apidoc(Blueprint):
    registered: bool
    def __init__(self, *args, **kwargs) -> None: ...
    def register(self, *args, **kwargs) -> None: ...

apidoc: Incomplete

def swagger_static(filename): ...
def ui_for(api): ...
