from _typeshed import Incomplete

def crossdomain(origin: Incomplete | None = ..., methods: Incomplete | None = ..., headers: Incomplete | None = ..., expose_headers: Incomplete | None = ..., max_age: int = ..., attach_to_all: bool = ..., automatic_options: bool = ..., credentials: bool = ...): ...
