from _typeshed import Incomplete

START_OF_DAY: Incomplete
END_OF_DAY: Incomplete
netloc_regex: Incomplete
email_regex: Incomplete
time_regex: Incomplete

def ipv4(value): ...
def ipv6(value): ...
def ip(value): ...

class URL:
    check: Incomplete
    ip: Incomplete
    local: Incomplete
    port: Incomplete
    auth: Incomplete
    schemes: Incomplete
    domains: Incomplete
    exclude: Incomplete
    def __init__(self, check: bool = ..., ip: bool = ..., local: bool = ..., port: bool = ..., auth: bool = ..., schemes: Incomplete | None = ..., domains: Incomplete | None = ..., exclude: Incomplete | None = ...) -> None: ...
    def error(self, value, details: Incomplete | None = ...) -> None: ...
    def __call__(self, value): ...
    @property
    def __schema__(self): ...

url: Incomplete

class email:
    check: Incomplete
    ip: Incomplete
    local: Incomplete
    domains: Incomplete
    exclude: Incomplete
    def __init__(self, check: bool = ..., ip: bool = ..., local: bool = ..., domains: Incomplete | None = ..., exclude: Incomplete | None = ...) -> None: ...
    def error(self, value, msg: Incomplete | None = ...) -> None: ...
    def is_ip(self, value): ...
    def __call__(self, value): ...
    @property
    def __schema__(self): ...

class regex:
    pattern: Incomplete
    re: Incomplete
    def __init__(self, pattern) -> None: ...
    def __call__(self, value): ...
    def __deepcopy__(self, memo): ...
    @property
    def __schema__(self): ...

def iso8601interval(value, argument: str = ...): ...
def date(value): ...
def natural(value, argument: str = ...): ...
def positive(value, argument: str = ...): ...

class int_range:
    low: Incomplete
    high: Incomplete
    argument: Incomplete
    def __init__(self, low, high, argument: str = ...) -> None: ...
    def __call__(self, value): ...
    @property
    def __schema__(self): ...

def boolean(value): ...
def datetime_from_rfc822(value): ...
def datetime_from_iso8601(value): ...
def date_from_iso8601(value): ...
