"""Remove labour_certificates_payout table

Revision ID: 02e7e4ed281d
Revises: 7a550048df32
Create Date: 2023-07-05 18:45:29.557800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e7e4ed281d'
down_revision = '7a550048df32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labour_certificates_payout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labour_certificates_payout',
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name='labour_certificates_payout_plan_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='labour_certificates_payout_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('transaction_id', name='labour_certificates_payout_pkey')
    )
    # ### end Alembic commands ###
