"""add column rejection_date to plan table

Revision ID: 1378a396f7f4
Revises: 8245d6c57ca5
Create Date: 2024-09-08 21:20:12.418718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1378a396f7f4'
down_revision = '8245d6c57ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_review', schema=None) as batch_op:
        batch_op.drop_column('rejection_date')

    # ### end Alembic commands ###
