"""delete offer table

Revision ID: 803d7861bcbc
Revises: 1233ec1448c0
Create Date: 2021-11-01 21:49:07.346121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '803d7861bcbc'
down_revision = '1233ec1448c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cr_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=5000), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name='offer_plan_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='offer_pkey')
    )
    # ### end Alembic commands ###
