"""Remove obsolete expired and is_active fields from Plan

Revision ID: 925b1eb7c332
Revises: a8ce3323df52
Create Date: 2023-03-20 09:59:26.937678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925b1eb7c332'
down_revision = 'a8ce3323df52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('expired')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
