"""Make social_accounting.account and member.account non-nullable

Revision ID: bdb92a1ce32c
Revises: e329522f1f5b
Create Date: 2023-01-12 12:37:21.402834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bdb92a1ce32c"
down_revision = "e329522f1f5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("member") as batch_op:
        batch_op.add_column(sa.Column("account", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "member_account_fkey", "account", ["account"], ["id"]
        )
    with op.batch_alter_table("social_accounting") as batch_op:
        batch_op.add_column(sa.Column("account", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "social_accounting_account_fkey", "account", ["account"], ["id"]
        )
    op.execute(
        """
        UPDATE social_accounting
        SET account = (
            SELECT id
            FROM account
            WHERE social_accounting.id = account.account_owner_social_accounting
        )
        """
    )
    op.execute(
        """
        UPDATE member
        SET account = (
            SELECT id
            FROM account
            WHERE member.id = account.account_owner_member
        )
        """
    )
    with op.batch_alter_table("member") as batch_op:
        batch_op.alter_column("account", nullable=False)
    with op.batch_alter_table("social_accounting") as batch_op:
        batch_op.alter_column("account", nullable=False)
    with op.batch_alter_table("account") as batch_op:
        batch_op.drop_constraint(
            "account_account_owner_social_accounting_fkey", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "account_account_owner_member_fkey", type_="foreignkey"
        )
        batch_op.drop_column("account_owner_social_accounting")
        batch_op.drop_column("account_owner_member")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account") as batch_op:
        batch_op.add_column(
            sa.Column(
                "account_owner_member", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "account_owner_social_accounting",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            "account_account_owner_member_fkey",
            "member",
            ["account_owner_member"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "account_account_owner_social_accounting_fkey",
            "social_accounting",
            ["account_owner_social_accounting"],
            ["id"],
        )
    op.execute(
        """
        UPDATE account
        SET account_owner_member = (
            SELECT id
            FROM member
            WHERE member.account = account.id
        )
        """
    )
    op.execute(
        """
        UPDATE account
        SET account_owner_social_accounting = (
            SELECT id
            FROM social_accounting
            WHERE social_accounting.account = account.id
        )
        """
    )
    with op.batch_alter_table("social_accounting") as batch_op:
        batch_op.drop_constraint("social_accounting_account_fkey", type_="foreignkey")
        batch_op.drop_column("account")
    with op.batch_alter_table("member") as batch_op:
        batch_op.drop_constraint("member_account_fkey", type_="foreignkey")
        batch_op.drop_column("account")
    # ### end Alembic commands ###
