"""create coordination transfer request table

Revision ID: c389d9c0145e
Revises: e25cf496eef3
Create Date: 2023-11-21 20:56:39.009835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c389d9c0145e'
down_revision = 'e25cf496eef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordination_transfer_request',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('requesting_coordination_tenure', sa.String(), nullable=False),
    sa.Column('candidate', sa.String(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate'], ['company.id'], ),
    sa.ForeignKeyConstraint(['requesting_coordination_tenure'], ['coordination_tenure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coordination_transfer_request')
    # ### end Alembic commands ###
