"""change purpose field in Transaction to plan

Revision ID: 02e783cb0f54
Revises: 8cdaf3b82da6
Create Date: 2023-06-07 23:02:41.451392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e783cb0f54'
down_revision = '8cdaf3b82da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(), nullable=True))
        batch_op.create_foreign_key('transaction_plan_fkey', 'plan', ['plan'], ['id'])
    op.execute('''
UPDATE transaction
SET plan = substring(purpose, 10)
WHERE purpose NOT LIKE 'Lohn';
    ''')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.execute('''
UPDATE transaction
SET purpose = 'Plan-Id: ' || plan
WHERE plan IS NOT NULL;

UPDATE transaction
SET purpose = 'Lohn'
WHERE plan IS NULL;
    ''')
    
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_plan_fkey', type_='foreignkey')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
