"""Make company account columns non-nullable

Revision ID: 1603b0734dab
Revises: 52e3a1f4fc9a
Create Date: 2023-01-04 16:06:10.918367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1603b0734dab'
down_revision = '52e3a1f4fc9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company') as batch_op:
        batch_op.alter_column('p_account',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('r_account',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('a_account',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('prd_account',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company') as batch_op:
        batch_op.alter_column('prd_account',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('a_account',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('r_account',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('p_account',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
    # ### end Alembic commands ###
