"""Remove obsolete field PlanReview.approval_reason

Revision ID: 2185d9d4448f
Revises: 3b00c719fe52
Create Date: 2023-02-13 22:23:58.823436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2185d9d4448f'
down_revision = '3b00c719fe52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_review', schema=None) as batch_op:
        batch_op.drop_column('approval_reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_reason', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
