"""Remove expiration_relative column for Plan

Revision ID: 51153c9ba707
Revises: ddb975a7f24b
Create Date: 2022-06-24 15:35:53.015170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51153c9ba707'
down_revision = 'ddb975a7f24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan') as batch_op:
        batch_op.drop_column('expiration_relative')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan') as batch_op:
        batch_op.add_column(sa.Column('expiration_relative', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
