"""Message points to user action

Revision ID: 5e541f042231
Revises: 5f166cdf3014
Create Date: 2022-02-02 16:39:34.326536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e541f042231'
down_revision = '5f166cdf3014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message') as batch_op:
        batch_op.add_column(sa.Column('user_action', sa.String(), nullable=True))
        batch_op.create_foreign_key('message_user_action_fkey', 'user_action', ['user_action'], ['id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message') as batch_op:
        batch_op.drop_constraint('message_user_action_fkey', type_='foreignkey')
        batch_op.drop_column('user_action')
    # ### end Alembic commands ###
