"""Create user action model

Revision ID: 5f166cdf3014
Revises: fb89625b2d12
Create Date: 2022-02-02 16:38:55.900265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f166cdf3014'
down_revision = 'fb89625b2d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('action_type', sa.Enum('answer_invite', 'answer_cooperation_request', name='useractiontype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('message', 'user_action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_action', postgresql.ENUM('answer_invite', name='useraction'), autoincrement=False, nullable=True))
    op.execute('DROP TYPE IF EXISTS useractiontype CASCADE')
    op.drop_table('user_action')
    # ### end Alembic commands ###
