"""create cancelled_hours_worked table

Revision ID: 78c97a89f4f9
Revises: e0cb944a36b2
Create Date: 2025-02-01 22:33:42.489256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c97a89f4f9'
down_revision: Union[str, None] = 'e0cb944a36b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancelled_hours_worked',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('registered_entry', sa.String(), nullable=False),
    sa.Column('transaction', sa.String(), nullable=False),
    sa.Column('cancelled_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registered_entry'], ['registered_hours_worked.id'], ),
    sa.ForeignKeyConstraint(['transaction'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cancelled_hours_worked')
    # ### end Alembic commands ###
