"""add column rejection_date

Revision ID: a307cd28f26a
Revises: 1378a396f7f4
Create Date: 2024-09-13 23:06:10.813418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a307cd28f26a'
down_revision = '1378a396f7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('rejection_date')

    # ### end Alembic commands ###
