"""Create CompanyPurchase and ConsumerPurchase, delete Purchase

Revision ID: a8ce3323df52
Revises: 15d33dfe8ec7
Create Date: 2023-03-04 18:25:03.348552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a8ce3323df52"
down_revision = "15d33dfe8ec7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_purchase",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("plan_id", sa.String(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "consumer_purchase",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("plan_id", sa.String(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("purchase")
    postgresql.ENUM(
        "means_of_prod",
        "raw_materials",
        "consumption",
        name="purposesofpurchases",
    ).drop(bind=op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "purchase_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("plan_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("type_member", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("company", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("member", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("price_per_unit", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column("amount", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "purpose",
            postgresql.ENUM(
                "means_of_prod",
                "raw_materials",
                "consumption",
                name="purposesofpurchases",
                create_type=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company"], ["company.id"], name="purchase_company_fkey"
        ),
        sa.ForeignKeyConstraint(["member"], ["member.id"], name="purchase_member_fkey"),
        sa.ForeignKeyConstraint(["plan_id"], ["plan.id"], name="purchase_plan_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="purchase_pkey"),
    )
    op.drop_table("consumer_purchase")
    op.drop_table("company_purchase")
    # ### end Alembic commands ###
