"""master migration, add password reset request table

Revision ID: bd37d6e84f45
Revises: 1e58bf7b0729
Create Date: 2024-02-25 22:46:46.462855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd37d6e84f45'
down_revision = '1e58bf7b0729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_cooperation',
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('cooperation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cooperation'], ['cooperation.id'], ),
    sa.ForeignKeyConstraint(['plan'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('plan')
    )
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_constraint('plan_cooperation_fkey', type_='foreignkey')
        batch_op.drop_column('cooperation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooperation', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('plan_cooperation_fkey', 'cooperation', ['cooperation'], ['id'])

    op.drop_table('plan_cooperation')
    # ### end Alembic commands ###
