"""Make columns not nullable

Revision ID: e0cb944a36b2
Revises: 1378a396f7f4
Create Date: 2024-12-02 22:43:07.926449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0cb944a36b2'
down_revision: Union[str, None] = '1378a396f7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'member_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction', 'purpose',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'purpose',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('jobs', 'company_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'member_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
