class RendererAgg:
    def __init__(self, *args, **kwargs) -> None: ...
    def clear(self, *args, **kwargs): ...
    def copy_from_bbox(self, *args, **kwargs): ...
    def draw_gouraud_triangle(self, *args, **kwargs): ...
    def draw_gouraud_triangles(self, *args, **kwargs): ...
    def draw_image(self, *args, **kwargs): ...
    def draw_markers(self, *args, **kwargs): ...
    def draw_path(self, *args, **kwargs): ...
    def draw_path_collection(self, *args, **kwargs): ...
    def draw_quad_mesh(self, *args, **kwargs): ...
    def draw_text_image(self, *args, **kwargs): ...
    def restore_region(self, *args, **kwargs): ...
