from _typeshed import Incomplete
from matplotlib import cbook as cbook
from matplotlib._pylab_helpers import Gcf as Gcf
from matplotlib.backend_bases import FigureCanvasBase as FigureCanvasBase
from matplotlib.backend_bases import FigureManagerBase as FigureManagerBase
from matplotlib.backend_bases import NavigationToolbar2 as NavigationToolbar2
from matplotlib.backend_bases import ResizeEvent as ResizeEvent
from matplotlib.backend_bases import TimerBase as TimerBase
from matplotlib.backend_bases import _Backend

from . import _macosx
from .backend_agg import FigureCanvasAgg as FigureCanvasAgg

class TimerMac(_macosx.Timer, TimerBase): ...

class FigureCanvasMac(FigureCanvasAgg, _macosx.FigureCanvas, FigureCanvasBase):
    required_interactive_framework: str
    manager_class: Incomplete
    def __init__(self, figure) -> None: ...
    def draw(self) -> None: ...
    def draw_idle(self) -> None: ...
    def blit(self, bbox: Incomplete | None = None) -> None: ...
    def resize(self, width, height) -> None: ...
    def start_event_loop(self, timeout: int = 0) -> None: ...

class NavigationToolbar2Mac(_macosx.NavigationToolbar2, NavigationToolbar2):
    def __init__(self, canvas) -> None: ...
    def draw_rubberband(self, event, x0, y0, x1, y1) -> None: ...
    def remove_rubberband(self) -> None: ...
    def save_figure(self, *args) -> None: ...

class FigureManagerMac(_macosx.FigureManager, FigureManagerBase):
    def __init__(self, canvas, num) -> None: ...
    def destroy(self) -> None: ...
    @classmethod
    def start_main_loop(cls) -> None: ...
    def show(self) -> None: ...

class _BackendMac(_Backend):
    FigureCanvas = FigureCanvasMac
    FigureManager = FigureManagerMac
    mainloop: Incomplete
