from .. import cbook as cbook, font_manager as font_manager
from _typeshed import Incomplete
from matplotlib.backend_bases import FigureCanvasBase as FigureCanvasBase, FigureManagerBase as FigureManagerBase, GraphicsContextBase as GraphicsContextBase, RendererBase as RendererBase, _Backend
from matplotlib.font_manager import ttfFontProperty as ttfFontProperty
from matplotlib.path import Path as Path
from matplotlib.transforms import Affine2D as Affine2D

class RendererCairo(RendererBase):
    dpi: Incomplete
    gc: Incomplete
    width: Incomplete
    height: Incomplete
    text_ctx: Incomplete
    def __init__(self, dpi) -> None: ...
    def set_context(self, ctx) -> None: ...
    def draw_path(self, gc, path, transform, rgbFace: Incomplete | None = ...) -> None: ...
    def draw_markers(self, gc, marker_path, marker_trans, path, transform, rgbFace: Incomplete | None = ...) -> None: ...
    def draw_image(self, gc, x, y, im) -> None: ...
    def draw_text(self, gc, x, y, s, prop, angle, ismath: bool = ..., mtext: Incomplete | None = ...) -> None: ...
    def get_canvas_width_height(self): ...
    def get_text_width_height_descent(self, s, prop, ismath): ...
    def new_gc(self): ...
    def points_to_pixels(self, points): ...

class GraphicsContextCairo(GraphicsContextBase):
    renderer: Incomplete
    def __init__(self, renderer) -> None: ...
    def restore(self) -> None: ...
    def set_alpha(self, alpha) -> None: ...
    def set_antialiased(self, b) -> None: ...
    def get_antialiased(self): ...
    def set_capstyle(self, cs) -> None: ...
    def set_clip_rectangle(self, rectangle) -> None: ...
    def set_clip_path(self, path) -> None: ...
    def set_dashes(self, offset, dashes) -> None: ...
    def set_foreground(self, fg, isRGBA: Incomplete | None = ...) -> None: ...
    def get_rgb(self): ...
    def set_joinstyle(self, js) -> None: ...
    def set_linewidth(self, w) -> None: ...

class _CairoRegion:
    def __init__(self, slices, data) -> None: ...

class FigureCanvasCairo(FigureCanvasBase):
    def get_renderer(self): ...
    def copy_from_bbox(self, bbox): ...
    def restore_region(self, region) -> None: ...
    def print_png(self, fobj) -> None: ...
    def print_rgba(self, fobj) -> None: ...
    print_raw = print_rgba
    print_pdf: Incomplete
    print_ps: Incomplete
    print_svg: Incomplete
    print_svgz: Incomplete

class _BackendCairo(_Backend):
    backend_version: Incomplete
    FigureCanvas = FigureCanvasCairo
    FigureManager = FigureManagerBase
