from _typeshed import Incomplete

QT_API_PYQT6: str
QT_API_PYSIDE6: str
QT_API_PYQT5: str
QT_API_PYSIDE2: str
QT_API_ENV: Incomplete
QT_API = QT_API_PYQT6
QT_API = QT_API_PYSIDE6
QT_API = QT_API_PYQT5
QT_API = QT_API_PYSIDE2
