from enum import Enum

from _typeshed import Incomplete

class BackendFilter(Enum):
    INTERACTIVE: int
    NON_INTERACTIVE: int

class BackendRegistry:
    def __init__(self) -> None: ...
    def backend_for_gui_framework(self, framework): ...
    def is_valid_backend(self, backend): ...
    def list_all(self): ...
    def list_builtin(self, filter_: Incomplete | None = None): ...
    def list_gui_frameworks(self): ...
    def load_backend_module(self, backend): ...
    def resolve_backend(self, backend): ...
    def resolve_gui_or_backend(self, gui_or_backend): ...

backend_registry: Incomplete
