import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from arbeitszeit_flask.config.options import CONFIG_OPTIONS  # noqa: E402

DOCS_PATH = "docs/"


def make_rst_file(filename: str, content: str) -> None:
    os.makedirs(DOCS_PATH, exist_ok=True)
    filepath = os.path.join(DOCS_PATH, filename)
    with open(filepath, "w") as f:
        f.write(content)
    print(f"Created {filepath}")


def create_options_section() -> str:
    options_section = ""

    for option in CONFIG_OPTIONS:
        description_lines = []
        for paragraph in option.description_paragraphs:
            description_lines.append(f"   {paragraph}")

        description = "\n".join(description_lines)

        example = f"\n\n   Example: ``{option.example}``" if option.example else ""
        default = f"\n\n   Default: ``{option.default}``" if option.default else ""

        options_section += f"""
.. py:data:: {option.name}
   :no-index:

{description}{example}{default}
"""
    return options_section


if __name__ == "__main__":
    make_rst_file(
        "config_options_GENERATED.rst",
        f""".. this file is autogenerated - do not change it manually
        {create_options_section()}""",
    )
