class LazyString:
    def __init__(self, func, *args, **kwargs) -> None: ...
    def __getattr__(self, attr): ...
    def __len__(self) -> int: ...
    def __getitem__(self, key): ...
    def __iter__(self): ...
    def __contains__(self, item) -> bool: ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __mul__(self, other): ...
    def __rmul__(self, other): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __html__(self): ...
    def __hash__(self): ...
    def __mod__(self, other): ...
    def __rmod__(self, other): ...
