from _typeshed import Incomplete
from flask import session
from wtforms import Form
from wtforms.meta import DefaultMeta

from .i18n import translations as translations

SUBMIT_METHODS: Incomplete

class FlaskForm(Form):
    class Meta(DefaultMeta):
        csrf_class: Incomplete
        csrf_context = session
        def csrf(self): ...
        def csrf_secret(self): ...
        def csrf_field_name(self): ...
        def csrf_time_limit(self): ...
        def wrap_formdata(self, form, formdata): ...
        def get_translations(self, form): ...

    def __init__(self, formdata=..., **kwargs) -> None: ...
    def is_submitted(self): ...
    def validate_on_submit(self, extra_validators: Incomplete | None = None): ...
    def hidden_tag(self, *fields): ...
