from _typeshed import Incomplete
from flask import session
from werkzeug.utils import cached_property
from wtforms import Form
from wtforms.meta import DefaultMeta

from .i18n import translations as translations

SUBMIT_METHODS: Incomplete

class FlaskForm(Form):
    class Meta(DefaultMeta):
        csrf_class: Incomplete
        csrf_context = session
        @cached_property
        def csrf(self): ...
        @cached_property
        def csrf_secret(self): ...
        @cached_property
        def csrf_field_name(self): ...
        @cached_property
        def csrf_time_limit(self): ...
        def wrap_formdata(self, form, formdata): ...
        def get_translations(self, form): ...

    def __init__(self, formdata=..., **kwargs) -> None: ...
    def is_submitted(self): ...
    def validate_on_submit(self, extra_validators=None): ...
    def hidden_tag(self, *fields): ...
